packages:
  - apps/*
  - packages/*

minimumReleaseAge: 3333

minimumReleaseAgeExclude:
  - oxlint
  - oxfmt
  - '@oxlint/*'
  - '@oxfmt/*'

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  tinykeys: patches/tinykeys.patch
