packages:
  - apps/*
  - packages/*

minimumReleaseAge: 3333

minimumReleaseAgeExclude:
  - oxlint
  - oxfmt
  - oxlint-tsgolint
  - "@oxlint/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - esbuild
  - msw
  - sharp

patchedDependencies:
  three-forcegraph@1.43.4: patches/three-forcegraph.patch
  tinykeys: patches/tinykeys.patch
