// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOneTimeToken = `-- name: ConsumeOneTimeToken :one
UPDATE auth.one_time_tokens
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, email, token_type, token_hash, used_at, created_at, expires_at
`

// Atomic lookup-and-invalidate. The previous separate SELECT + UPDATE pair
// allowed two concurrent requests with the same code to both pass the
// IS NULL guard before either UPDATE landed; this single UPDATE is
// serialized by the row lock, and the RETURNING clause means only the
// winner gets a non-empty result. A second caller (or a stale/used token)
// gets pgx.ErrNoRows.
func (q *Queries) ConsumeOneTimeToken(ctx context.Context, tokenHash string) (AuthOneTimeToken, error) {
	row := q.db.QueryRow(ctx, consumeOneTimeToken, tokenHash)
	var i AuthOneTimeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenType,
		&i.TokenHash,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const consumeRefreshTokenByHash = `-- name: ConsumeRefreshTokenByHash :one
UPDATE auth.refresh_tokens AS rt
SET revoked_at = now(), updated_at = now()
FROM auth.sessions AS s
WHERE rt.session_id = s.id
  AND rt.token_hash = $1
  AND rt.revoked_at IS NULL
  AND rt.expires_at > now()
  AND s.revoked_at IS NULL
  AND s.not_after > now()
  AND s.refreshed_at > now() - $2::interval
RETURNING rt.id, rt.token_hash, rt.session_id, rt.user_id, rt.expires_at, rt.revoked_at, rt.created_at, rt.updated_at
`

type ConsumeRefreshTokenByHashParams struct {
	TokenHash         string          `json:"token_hash"`
	InactivityTimeout pgtype.Interval `json:"inactivity_timeout"`
}

func (q *Queries) ConsumeRefreshTokenByHash(ctx context.Context, arg ConsumeRefreshTokenByHashParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshTokenByHash, arg.TokenHash, arg.InactivityTimeout)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthEvent = `-- name: CreateAuthEvent :exec
INSERT INTO audit_log.auth_events (actor_id, actor_email, action, payload, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuthEventParams struct {
	ActorID    uuid.NullUUID      `json:"actor_id"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	Action     AuditLogAuthAction `json:"action"`
	Payload    []byte             `json:"payload"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error {
	_, err := q.db.Exec(ctx, createAuthEvent,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.Payload,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const createFlowState = `-- name: CreateFlowState :one
INSERT INTO auth.flow_state (auth_code, provider_type, authentication_method, email, user_id, redirect_uri, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, auth_code, provider_type, authentication_method, email, user_id, redirect_uri, created_at, updated_at, expires_at
`

type CreateFlowStateParams struct {
	AuthCode             string             `json:"auth_code"`
	ProviderType         string             `json:"provider_type"`
	AuthenticationMethod string             `json:"authentication_method"`
	Email                pgtype.Text        `json:"email"`
	UserID               uuid.NullUUID      `json:"user_id"`
	RedirectUri          pgtype.Text        `json:"redirect_uri"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateFlowState(ctx context.Context, arg CreateFlowStateParams) (AuthFlowState, error) {
	row := q.db.QueryRow(ctx, createFlowState,
		arg.AuthCode,
		arg.ProviderType,
		arg.AuthenticationMethod,
		arg.Email,
		arg.UserID,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	var i AuthFlowState
	err := row.Scan(
		&i.ID,
		&i.AuthCode,
		&i.ProviderType,
		&i.AuthenticationMethod,
		&i.Email,
		&i.UserID,
		&i.RedirectUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth.identities (user_id, provider, provider_id, identity_data, email, last_sign_in_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, user_id, provider, provider_id, identity_data, email, last_sign_in_at, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	Provider     string      `json:"provider"`
	ProviderID   string      `json:"provider_id"`
	IdentityData []byte      `json:"identity_data"`
	Email        pgtype.Text `json:"email"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.IdentityData,
		arg.Email,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.IdentityData,
		&i.Email,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOneTimeToken = `-- name: CreateOneTimeToken :one
INSERT INTO auth.one_time_tokens (user_id, email, token_type, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, email, token_type, token_hash, used_at, created_at, expires_at
`

type CreateOneTimeTokenParams struct {
	UserID    uuid.NullUUID        `json:"user_id"`
	Email     string               `json:"email"`
	TokenType AuthOneTimeTokenType `json:"token_type"`
	TokenHash string               `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz   `json:"expires_at"`
}

func (q *Queries) CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) (AuthOneTimeToken, error) {
	row := q.db.QueryRow(ctx, createOneTimeToken,
		arg.UserID,
		arg.Email,
		arg.TokenType,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthOneTimeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenType,
		&i.TokenHash,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth.refresh_tokens (token_hash, session_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, session_id, user_id, expires_at, revoked_at, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	TokenHash string             `json:"token_hash"`
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.SessionID,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth.sessions (user_id, not_after, user_agent, ip_address)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, not_after, refreshed_at, revoked_at, user_agent, ip_address, created_at, updated_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	NotAfter  pgtype.Timestamptz `json:"not_after"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.NotAfter,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotAfter,
		&i.RefreshedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (email, name, email_confirmed_at)
VALUES ($1, $2, $3)
RETURNING id, email, name, email_confirmed_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.EmailConfirmedAt)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.EmailConfirmedAt,
		&i.LastSignInAt,
		&i.RawAppMetaData,
		&i.RawUserMetaData,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowState = `-- name: DeleteFlowState :exec
DELETE FROM auth.flow_state
WHERE id = $1
`

func (q *Queries) DeleteFlowState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowState, id)
	return err
}

const getFlowStateByCode = `-- name: GetFlowStateByCode :one
SELECT id, auth_code, provider_type, authentication_method, email, user_id, redirect_uri, created_at, updated_at, expires_at FROM auth.flow_state
WHERE auth_code = $1 AND expires_at > now()
`

func (q *Queries) GetFlowStateByCode(ctx context.Context, authCode string) (AuthFlowState, error) {
	row := q.db.QueryRow(ctx, getFlowStateByCode, authCode)
	var i AuthFlowState
	err := row.Scan(
		&i.ID,
		&i.AuthCode,
		&i.ProviderType,
		&i.AuthenticationMethod,
		&i.Email,
		&i.UserID,
		&i.RedirectUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getIdentityByProviderID = `-- name: GetIdentityByProviderID :one
SELECT id, user_id, provider, provider_id, identity_data, email, last_sign_in_at, created_at, updated_at FROM auth.identities
WHERE provider = $1 AND provider_id = $2
`

type GetIdentityByProviderIDParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetIdentityByProviderID(ctx context.Context, arg GetIdentityByProviderIDParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderID, arg.Provider, arg.ProviderID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.IdentityData,
		&i.Email,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, email_confirmed_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, deleted_at, created_at, updated_at FROM auth.users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.EmailConfirmedAt,
		&i.LastSignInAt,
		&i.RawAppMetaData,
		&i.RawUserMetaData,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, email_confirmed_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, deleted_at, created_at, updated_at FROM auth.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.EmailConfirmedAt,
		&i.LastSignInAt,
		&i.RawAppMetaData,
		&i.RawUserMetaData,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidSession = `-- name: GetValidSession :one
SELECT id, user_id, not_after, refreshed_at, revoked_at, user_agent, ip_address, created_at, updated_at FROM auth.sessions
WHERE id = $1
  AND revoked_at IS NULL
  AND not_after > now()
  AND refreshed_at > now() - $2::interval
`

type GetValidSessionParams struct {
	ID                uuid.UUID       `json:"id"`
	InactivityTimeout pgtype.Interval `json:"inactivity_timeout"`
}

func (q *Queries) GetValidSession(ctx context.Context, arg GetValidSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getValidSession, arg.ID, arg.InactivityTimeout)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotAfter,
		&i.RefreshedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateOneTimeTokensByEmail = `-- name: InvalidateOneTimeTokensByEmail :exec
UPDATE auth.one_time_tokens
SET used_at = now()
WHERE email = $1 AND token_type = $2 AND used_at IS NULL
`

type InvalidateOneTimeTokensByEmailParams struct {
	Email     string               `json:"email"`
	TokenType AuthOneTimeTokenType `json:"token_type"`
}

func (q *Queries) InvalidateOneTimeTokensByEmail(ctx context.Context, arg InvalidateOneTimeTokensByEmailParams) error {
	_, err := q.db.Exec(ctx, invalidateOneTimeTokensByEmail, arg.Email, arg.TokenType)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE auth.refresh_tokens
SET revoked_at = now(), updated_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth.sessions
SET revoked_at = now(), updated_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE auth.refresh_tokens
SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth.sessions
SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionRefreshTokens = `-- name: RevokeSessionRefreshTokens :exec
UPDATE auth.refresh_tokens
SET revoked_at = now(), updated_at = now()
WHERE session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionRefreshTokens(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionRefreshTokens, sessionID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE auth.users
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateIdentityLastSignIn = `-- name: UpdateIdentityLastSignIn :exec
UPDATE auth.identities
SET last_sign_in_at = now(), identity_data = $3, email = $4, updated_at = now()
WHERE provider = $1 AND provider_id = $2
`

type UpdateIdentityLastSignInParams struct {
	Provider     string      `json:"provider"`
	ProviderID   string      `json:"provider_id"`
	IdentityData []byte      `json:"identity_data"`
	Email        pgtype.Text `json:"email"`
}

func (q *Queries) UpdateIdentityLastSignIn(ctx context.Context, arg UpdateIdentityLastSignInParams) error {
	_, err := q.db.Exec(ctx, updateIdentityLastSignIn,
		arg.Provider,
		arg.ProviderID,
		arg.IdentityData,
		arg.Email,
	)
	return err
}

const updateSessionRefreshedAt = `-- name: UpdateSessionRefreshedAt :exec
UPDATE auth.sessions
SET refreshed_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) UpdateSessionRefreshedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionRefreshedAt, id)
	return err
}

const updateUserLastSignIn = `-- name: UpdateUserLastSignIn :exec
UPDATE auth.users
SET last_sign_in_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastSignIn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastSignIn, id)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE auth.users
SET name = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, name, email_confirmed_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, deleted_at, created_at, updated_at
`

type UpdateUserNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.EmailConfirmedAt,
		&i.LastSignInAt,
		&i.RawAppMetaData,
		&i.RawUserMetaData,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
