// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSubscriptionExists = `-- name: EnsureSubscriptionExists :one
INSERT INTO kuku.subscriptions (user_id, plan, status)
VALUES ($1, 'FREE', 'ACTIVE')
ON CONFLICT (user_id) DO UPDATE SET updated_at = now()
RETURNING id, user_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at
`

func (q *Queries) EnsureSubscriptionExists(ctx context.Context, userID uuid.UUID) (KukuSubscription, error) {
	row := q.db.QueryRow(ctx, ensureSubscriptionExists, userID)
	var i KukuSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentPeriodUsage = `-- name: GetCurrentPeriodUsage :one
SELECT
  COALESCE(SUM(ai_requests), 0)::INTEGER AS total_ai_requests,
  COALESCE(SUM(tokens_k), 0)::REAL AS total_tokens_k
FROM kuku.usage_stats
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
`

type GetCurrentPeriodUsageParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetCurrentPeriodUsageRow struct {
	TotalAiRequests int32   `json:"total_ai_requests"`
	TotalTokensK    float32 `json:"total_tokens_k"`
}

func (q *Queries) GetCurrentPeriodUsage(ctx context.Context, arg GetCurrentPeriodUsageParams) (GetCurrentPeriodUsageRow, error) {
	row := q.db.QueryRow(ctx, getCurrentPeriodUsage, arg.UserID, arg.Date, arg.Date_2)
	var i GetCurrentPeriodUsageRow
	err := row.Scan(&i.TotalAiRequests, &i.TotalTokensK)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at FROM kuku.subscriptions
WHERE user_id = $1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (KukuSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i KukuSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsageStatsByUserAndDateRange = `-- name: GetUsageStatsByUserAndDateRange :many
SELECT id, user_id, date, ai_requests, tokens_k::REAL AS tokens_k, created_at, updated_at
FROM kuku.usage_stats
WHERE user_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type GetUsageStatsByUserAndDateRangeParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetUsageStatsByUserAndDateRangeRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Date       pgtype.Date        `json:"date"`
	AiRequests int32              `json:"ai_requests"`
	TokensK    float32            `json:"tokens_k"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Explicit column list so the tokens_k cast pins sqlc's generated Go type
// (float32) regardless of the storage type. Storage is NUMERIC so SUM
// aggregates are exact; the cast here is lossless for display (REAL has
// more than enough precision for per-day token counts).
func (q *Queries) GetUsageStatsByUserAndDateRange(ctx context.Context, arg GetUsageStatsByUserAndDateRangeParams) ([]GetUsageStatsByUserAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getUsageStatsByUserAndDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageStatsByUserAndDateRangeRow
	for rows.Next() {
		var i GetUsageStatsByUserAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.AiRequests,
			&i.TokensK,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
