// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLogAuthAction string

const (
	AuditLogAuthActionLogin             AuditLogAuthAction = "login"
	AuditLogAuthActionLogout            AuditLogAuthAction = "logout"
	AuditLogAuthActionSignup            AuditLogAuthAction = "signup"
	AuditLogAuthActionTokenRefreshed    AuditLogAuthAction = "token_refreshed"
	AuditLogAuthActionTokenRevoked      AuditLogAuthAction = "token_revoked"
	AuditLogAuthActionUserModified      AuditLogAuthAction = "user_modified"
	AuditLogAuthActionUserDeleted       AuditLogAuthAction = "user_deleted"
	AuditLogAuthActionEmailOtpRequested AuditLogAuthAction = "email_otp_requested"
	AuditLogAuthActionEmailOtpVerified  AuditLogAuthAction = "email_otp_verified"
	AuditLogAuthActionIdentityLinked    AuditLogAuthAction = "identity_linked"
	AuditLogAuthActionIdentityUnlinked  AuditLogAuthAction = "identity_unlinked"
)

func (e *AuditLogAuthAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditLogAuthAction(s)
	case string:
		*e = AuditLogAuthAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditLogAuthAction: %T", src)
	}
	return nil
}

type NullAuditLogAuthAction struct {
	AuditLogAuthAction AuditLogAuthAction `json:"audit_log_auth_action"`
	Valid              bool               `json:"valid"` // Valid is true if AuditLogAuthAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditLogAuthAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditLogAuthAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditLogAuthAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditLogAuthAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditLogAuthAction), nil
}

type AuthOneTimeTokenType string

const (
	AuthOneTimeTokenTypeEmailAuth   AuthOneTimeTokenType = "email_auth"
	AuthOneTimeTokenTypeEmailChange AuthOneTimeTokenType = "email_change"
	AuthOneTimeTokenTypeDesktopAuth AuthOneTimeTokenType = "desktop_auth"
)

func (e *AuthOneTimeTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOneTimeTokenType(s)
	case string:
		*e = AuthOneTimeTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOneTimeTokenType: %T", src)
	}
	return nil
}

type NullAuthOneTimeTokenType struct {
	AuthOneTimeTokenType AuthOneTimeTokenType `json:"auth_one_time_token_type"`
	Valid                bool                 `json:"valid"` // Valid is true if AuthOneTimeTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOneTimeTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOneTimeTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOneTimeTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOneTimeTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOneTimeTokenType), nil
}

type KukuPlan string

const (
	KukuPlanFREE  KukuPlan = "FREE"
	KukuPlanPRO   KukuPlan = "PRO"
	KukuPlanULTRA KukuPlan = "ULTRA"
)

func (e *KukuPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuPlan(s)
	case string:
		*e = KukuPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuPlan: %T", src)
	}
	return nil
}

type NullKukuPlan struct {
	KukuPlan KukuPlan `json:"kuku_plan"`
	Valid    bool     `json:"valid"` // Valid is true if KukuPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuPlan) Scan(value interface{}) error {
	if value == nil {
		ns.KukuPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuPlan), nil
}

type KukuSubscriptionStatus string

const (
	KukuSubscriptionStatusACTIVE   KukuSubscriptionStatus = "ACTIVE"
	KukuSubscriptionStatusCANCELED KukuSubscriptionStatus = "CANCELED"
)

func (e *KukuSubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSubscriptionStatus(s)
	case string:
		*e = KukuSubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSubscriptionStatus: %T", src)
	}
	return nil
}

type NullKukuSubscriptionStatus struct {
	KukuSubscriptionStatus KukuSubscriptionStatus `json:"kuku_subscription_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if KukuSubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSubscriptionStatus), nil
}

type AuditLogAuthEvent struct {
	ID         uuid.UUID          `json:"id"`
	ActorID    uuid.NullUUID      `json:"actor_id"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	Action     AuditLogAuthAction `json:"action"`
	Payload    []byte             `json:"payload"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthFlowState struct {
	ID                   uuid.UUID          `json:"id"`
	AuthCode             string             `json:"auth_code"`
	ProviderType         string             `json:"provider_type"`
	AuthenticationMethod string             `json:"authentication_method"`
	Email                pgtype.Text        `json:"email"`
	UserID               uuid.NullUUID      `json:"user_id"`
	RedirectUri          pgtype.Text        `json:"redirect_uri"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

type AuthIdentity struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	ProviderID   string             `json:"provider_id"`
	IdentityData []byte             `json:"identity_data"`
	Email        pgtype.Text        `json:"email"`
	LastSignInAt pgtype.Timestamptz `json:"last_sign_in_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuthOneTimeToken struct {
	ID        uuid.UUID            `json:"id"`
	UserID    uuid.NullUUID        `json:"user_id"`
	Email     string               `json:"email"`
	TokenType AuthOneTimeTokenType `json:"token_type"`
	TokenHash string               `json:"token_hash"`
	UsedAt    pgtype.Timestamptz   `json:"used_at"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	ExpiresAt pgtype.Timestamptz   `json:"expires_at"`
}

type AuthRefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	TokenHash string             `json:"token_hash"`
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	NotAfter    pgtype.Timestamptz `json:"not_after"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuthUser struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
	LastSignInAt     pgtype.Timestamptz `json:"last_sign_in_at"`
	RawAppMetaData   []byte             `json:"raw_app_meta_data"`
	RawUserMetaData  []byte             `json:"raw_user_meta_data"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type KukuSubscription struct {
	ID                 uuid.UUID              `json:"id"`
	UserID             uuid.UUID              `json:"user_id"`
	Plan               KukuPlan               `json:"plan"`
	Status             KukuSubscriptionStatus `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz     `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz     `json:"current_period_end"`
	CancelAtPeriodEnd  bool                   `json:"cancel_at_period_end"`
	CreatedAt          pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz     `json:"updated_at"`
}

type KukuUsageStat struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Date       pgtype.Date        `json:"date"`
	AiRequests int32              `json:"ai_requests"`
	TokensK    pgtype.Numeric     `json:"tokens_k"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
