// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLogAuthAction string

const (
	AuditLogAuthActionLogin             AuditLogAuthAction = "login"
	AuditLogAuthActionLogout            AuditLogAuthAction = "logout"
	AuditLogAuthActionSignup            AuditLogAuthAction = "signup"
	AuditLogAuthActionTokenRefreshed    AuditLogAuthAction = "token_refreshed"
	AuditLogAuthActionTokenRevoked      AuditLogAuthAction = "token_revoked"
	AuditLogAuthActionUserModified      AuditLogAuthAction = "user_modified"
	AuditLogAuthActionUserDeleted       AuditLogAuthAction = "user_deleted"
	AuditLogAuthActionEmailOtpRequested AuditLogAuthAction = "email_otp_requested"
	AuditLogAuthActionEmailOtpVerified  AuditLogAuthAction = "email_otp_verified"
	AuditLogAuthActionIdentityLinked    AuditLogAuthAction = "identity_linked"
	AuditLogAuthActionIdentityUnlinked  AuditLogAuthAction = "identity_unlinked"
)

func (e *AuditLogAuthAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditLogAuthAction(s)
	case string:
		*e = AuditLogAuthAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditLogAuthAction: %T", src)
	}
	return nil
}

type NullAuditLogAuthAction struct {
	AuditLogAuthAction AuditLogAuthAction `json:"audit_log_auth_action"`
	Valid              bool               `json:"valid"` // Valid is true if AuditLogAuthAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditLogAuthAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditLogAuthAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditLogAuthAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditLogAuthAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditLogAuthAction), nil
}

type AuthOneTimeTokenType string

const (
	AuthOneTimeTokenTypeEmailAuth   AuthOneTimeTokenType = "email_auth"
	AuthOneTimeTokenTypeEmailChange AuthOneTimeTokenType = "email_change"
	AuthOneTimeTokenTypeDesktopAuth AuthOneTimeTokenType = "desktop_auth"
)

func (e *AuthOneTimeTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOneTimeTokenType(s)
	case string:
		*e = AuthOneTimeTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOneTimeTokenType: %T", src)
	}
	return nil
}

type NullAuthOneTimeTokenType struct {
	AuthOneTimeTokenType AuthOneTimeTokenType `json:"auth_one_time_token_type"`
	Valid                bool                 `json:"valid"` // Valid is true if AuthOneTimeTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOneTimeTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOneTimeTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOneTimeTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOneTimeTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOneTimeTokenType), nil
}

type KukuPlan string

const (
	KukuPlanFREE  KukuPlan = "FREE"
	KukuPlanPRO   KukuPlan = "PRO"
	KukuPlanULTRA KukuPlan = "ULTRA"
)

func (e *KukuPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuPlan(s)
	case string:
		*e = KukuPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuPlan: %T", src)
	}
	return nil
}

type NullKukuPlan struct {
	KukuPlan KukuPlan `json:"kuku_plan"`
	Valid    bool     `json:"valid"` // Valid is true if KukuPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuPlan) Scan(value interface{}) error {
	if value == nil {
		ns.KukuPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuPlan), nil
}

type KukuSubscriptionStatus string

const (
	KukuSubscriptionStatusACTIVE   KukuSubscriptionStatus = "ACTIVE"
	KukuSubscriptionStatusCANCELED KukuSubscriptionStatus = "CANCELED"
)

func (e *KukuSubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSubscriptionStatus(s)
	case string:
		*e = KukuSubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSubscriptionStatus: %T", src)
	}
	return nil
}

type NullKukuSubscriptionStatus struct {
	KukuSubscriptionStatus KukuSubscriptionStatus `json:"kuku_subscription_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if KukuSubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSubscriptionStatus), nil
}

type KukuSyncAccountKeyRecipientType string

const (
	KukuSyncAccountKeyRecipientTypeRecoveryPhrase KukuSyncAccountKeyRecipientType = "recovery_phrase"
	KukuSyncAccountKeyRecipientTypeDevice         KukuSyncAccountKeyRecipientType = "device"
)

func (e *KukuSyncAccountKeyRecipientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncAccountKeyRecipientType(s)
	case string:
		*e = KukuSyncAccountKeyRecipientType(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncAccountKeyRecipientType: %T", src)
	}
	return nil
}

type NullKukuSyncAccountKeyRecipientType struct {
	KukuSyncAccountKeyRecipientType KukuSyncAccountKeyRecipientType `json:"kuku_sync_account_key_recipient_type"`
	Valid                           bool                            `json:"valid"` // Valid is true if KukuSyncAccountKeyRecipientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncAccountKeyRecipientType) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncAccountKeyRecipientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncAccountKeyRecipientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncAccountKeyRecipientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncAccountKeyRecipientType), nil
}

type KukuSyncCommitKind string

const (
	KukuSyncCommitKindIncremental KukuSyncCommitKind = "incremental"
	KukuSyncCommitKindMerge       KukuSyncCommitKind = "merge"
	KukuSyncCommitKindCheckpoint  KukuSyncCommitKind = "checkpoint"
)

func (e *KukuSyncCommitKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncCommitKind(s)
	case string:
		*e = KukuSyncCommitKind(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncCommitKind: %T", src)
	}
	return nil
}

type NullKukuSyncCommitKind struct {
	KukuSyncCommitKind KukuSyncCommitKind `json:"kuku_sync_commit_kind"`
	Valid              bool               `json:"valid"` // Valid is true if KukuSyncCommitKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncCommitKind) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncCommitKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncCommitKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncCommitKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncCommitKind), nil
}

type KukuSyncCommitObjectRole string

const (
	KukuSyncCommitObjectRoleBody           KukuSyncCommitObjectRole = "body"
	KukuSyncCommitObjectRoleContentPack    KukuSyncCommitObjectRole = "content_pack"
	KukuSyncCommitObjectRoleCheckpointPack KukuSyncCommitObjectRole = "checkpoint_pack"
	KukuSyncCommitObjectRoleLargeObject    KukuSyncCommitObjectRole = "large_object"
)

func (e *KukuSyncCommitObjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncCommitObjectRole(s)
	case string:
		*e = KukuSyncCommitObjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncCommitObjectRole: %T", src)
	}
	return nil
}

type NullKukuSyncCommitObjectRole struct {
	KukuSyncCommitObjectRole KukuSyncCommitObjectRole `json:"kuku_sync_commit_object_role"`
	Valid                    bool                     `json:"valid"` // Valid is true if KukuSyncCommitObjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncCommitObjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncCommitObjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncCommitObjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncCommitObjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncCommitObjectRole), nil
}

type KukuSyncKeyRecipientType string

const (
	KukuSyncKeyRecipientTypePassphrase KukuSyncKeyRecipientType = "passphrase"
	KukuSyncKeyRecipientTypeDevice     KukuSyncKeyRecipientType = "device"
)

func (e *KukuSyncKeyRecipientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncKeyRecipientType(s)
	case string:
		*e = KukuSyncKeyRecipientType(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncKeyRecipientType: %T", src)
	}
	return nil
}

type NullKukuSyncKeyRecipientType struct {
	KukuSyncKeyRecipientType KukuSyncKeyRecipientType `json:"kuku_sync_key_recipient_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if KukuSyncKeyRecipientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncKeyRecipientType) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncKeyRecipientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncKeyRecipientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncKeyRecipientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncKeyRecipientType), nil
}

type KukuSyncObjectErrorReason string

const (
	KukuSyncObjectErrorReasonUploadExpired        KukuSyncObjectErrorReason = "upload_expired"
	KukuSyncObjectErrorReasonChecksumMismatch     KukuSyncObjectErrorReason = "checksum_mismatch"
	KukuSyncObjectErrorReasonSizeMismatch         KukuSyncObjectErrorReason = "size_mismatch"
	KukuSyncObjectErrorReasonStorageProviderError KukuSyncObjectErrorReason = "storage_provider_error"
	KukuSyncObjectErrorReasonQuotaExceeded        KukuSyncObjectErrorReason = "quota_exceeded"
	KukuSyncObjectErrorReasonCanceled             KukuSyncObjectErrorReason = "canceled"
)

func (e *KukuSyncObjectErrorReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncObjectErrorReason(s)
	case string:
		*e = KukuSyncObjectErrorReason(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncObjectErrorReason: %T", src)
	}
	return nil
}

type NullKukuSyncObjectErrorReason struct {
	KukuSyncObjectErrorReason KukuSyncObjectErrorReason `json:"kuku_sync_object_error_reason"`
	Valid                     bool                      `json:"valid"` // Valid is true if KukuSyncObjectErrorReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncObjectErrorReason) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncObjectErrorReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncObjectErrorReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncObjectErrorReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncObjectErrorReason), nil
}

type KukuSyncObjectKind string

const (
	KukuSyncObjectKindCommitBody     KukuSyncObjectKind = "commit_body"
	KukuSyncObjectKindContentPack    KukuSyncObjectKind = "content_pack"
	KukuSyncObjectKindCheckpointPack KukuSyncObjectKind = "checkpoint_pack"
	KukuSyncObjectKindLargeObject    KukuSyncObjectKind = "large_object"
)

func (e *KukuSyncObjectKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncObjectKind(s)
	case string:
		*e = KukuSyncObjectKind(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncObjectKind: %T", src)
	}
	return nil
}

type NullKukuSyncObjectKind struct {
	KukuSyncObjectKind KukuSyncObjectKind `json:"kuku_sync_object_kind"`
	Valid              bool               `json:"valid"` // Valid is true if KukuSyncObjectKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncObjectKind) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncObjectKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncObjectKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncObjectKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncObjectKind), nil
}

type KukuSyncObjectState string

const (
	KukuSyncObjectStateReserved  KukuSyncObjectState = "reserved"
	KukuSyncObjectStatePending   KukuSyncObjectState = "pending"
	KukuSyncObjectStateAvailable KukuSyncObjectState = "available"
	KukuSyncObjectStateFailed    KukuSyncObjectState = "failed"
	KukuSyncObjectStateDeleted   KukuSyncObjectState = "deleted"
)

func (e *KukuSyncObjectState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncObjectState(s)
	case string:
		*e = KukuSyncObjectState(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncObjectState: %T", src)
	}
	return nil
}

type NullKukuSyncObjectState struct {
	KukuSyncObjectState KukuSyncObjectState `json:"kuku_sync_object_state"`
	Valid               bool                `json:"valid"` // Valid is true if KukuSyncObjectState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncObjectState) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncObjectState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncObjectState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncObjectState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncObjectState), nil
}

type KukuSyncStorageProvider string

const (
	KukuSyncStorageProviderLocal        KukuSyncStorageProvider = "local"
	KukuSyncStorageProviderS3Compatible KukuSyncStorageProvider = "s3_compatible"
)

func (e *KukuSyncStorageProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KukuSyncStorageProvider(s)
	case string:
		*e = KukuSyncStorageProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for KukuSyncStorageProvider: %T", src)
	}
	return nil
}

type NullKukuSyncStorageProvider struct {
	KukuSyncStorageProvider KukuSyncStorageProvider `json:"kuku_sync_storage_provider"`
	Valid                   bool                    `json:"valid"` // Valid is true if KukuSyncStorageProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKukuSyncStorageProvider) Scan(value interface{}) error {
	if value == nil {
		ns.KukuSyncStorageProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KukuSyncStorageProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKukuSyncStorageProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KukuSyncStorageProvider), nil
}

type AuditLogAuthEvent struct {
	ID         uuid.UUID          `json:"id"`
	ActorID    uuid.NullUUID      `json:"actor_id"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	Action     AuditLogAuthAction `json:"action"`
	Payload    []byte             `json:"payload"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthFlowState struct {
	ID                   uuid.UUID          `json:"id"`
	AuthCode             string             `json:"auth_code"`
	ProviderType         string             `json:"provider_type"`
	AuthenticationMethod string             `json:"authentication_method"`
	Email                pgtype.Text        `json:"email"`
	UserID               uuid.NullUUID      `json:"user_id"`
	RedirectUri          pgtype.Text        `json:"redirect_uri"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

type AuthIdentity struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	ProviderID   string             `json:"provider_id"`
	IdentityData []byte             `json:"identity_data"`
	Email        pgtype.Text        `json:"email"`
	LastSignInAt pgtype.Timestamptz `json:"last_sign_in_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuthOneTimeToken struct {
	ID        uuid.UUID            `json:"id"`
	UserID    uuid.NullUUID        `json:"user_id"`
	Email     string               `json:"email"`
	TokenType AuthOneTimeTokenType `json:"token_type"`
	TokenHash string               `json:"token_hash"`
	UsedAt    pgtype.Timestamptz   `json:"used_at"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	ExpiresAt pgtype.Timestamptz   `json:"expires_at"`
}

type AuthRefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	TokenHash string             `json:"token_hash"`
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	NotAfter    pgtype.Timestamptz `json:"not_after"`
	RefreshedAt pgtype.Timestamptz `json:"refreshed_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuthUser struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	EmailConfirmedAt pgtype.Timestamptz `json:"email_confirmed_at"`
	LastSignInAt     pgtype.Timestamptz `json:"last_sign_in_at"`
	RawAppMetaData   []byte             `json:"raw_app_meta_data"`
	RawUserMetaData  []byte             `json:"raw_user_meta_data"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type KukuSubscription struct {
	ID                 uuid.UUID              `json:"id"`
	UserID             uuid.UUID              `json:"user_id"`
	Plan               KukuPlan               `json:"plan"`
	Status             KukuSubscriptionStatus `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz     `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz     `json:"current_period_end"`
	CancelAtPeriodEnd  bool                   `json:"cancel_at_period_end"`
	CreatedAt          pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz     `json:"updated_at"`
}

type KukuSyncAccountKey struct {
	UserID        uuid.UUID          `json:"user_id"`
	AccountKeyID  string             `json:"account_key_id"`
	CryptoVersion string             `json:"crypto_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type KukuSyncAccountKeyEnvelope struct {
	UserID            uuid.UUID                       `json:"user_id"`
	AccountKeyID      string                          `json:"account_key_id"`
	EnvelopeID        string                          `json:"envelope_id"`
	RecipientType     KukuSyncAccountKeyRecipientType `json:"recipient_type"`
	KeyVersion        int64                           `json:"key_version"`
	KdfParams         []byte                          `json:"kdf_params"`
	EncryptedEnvelope []byte                          `json:"encrypted_envelope"`
	CreatedAt         pgtype.Timestamptz              `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz              `json:"updated_at"`
}

type KukuSyncCommit struct {
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	CommitID             string             `json:"commit_id"`
	CommitKind           KukuSyncCommitKind `json:"commit_kind"`
	AuthorDeviceID       uuid.UUID          `json:"author_device_id"`
	DeviceSeq            int64              `json:"device_seq"`
	ParentCommitIds      []string           `json:"parent_commit_ids"`
	BodyObjectID         string             `json:"body_object_id"`
	BodyCiphertextSha256 string             `json:"body_ciphertext_sha256"`
	BodySizeBytes        int64              `json:"body_size_bytes"`
	ReferencedObjectIds  []string           `json:"referenced_object_ids"`
	Signature            []byte             `json:"signature"`
	ServerSeq            pgtype.Int8        `json:"server_seq"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ExpectedHeadCommitID pgtype.Text        `json:"expected_head_commit_id"`
}

type KukuSyncCommitObject struct {
	WorkspaceID uuid.UUID                `json:"workspace_id"`
	CommitID    string                   `json:"commit_id"`
	ObjectID    string                   `json:"object_id"`
	ObjectRole  KukuSyncCommitObjectRole `json:"object_role"`
}

type KukuSyncDevice struct {
	ID                  uuid.UUID          `json:"id"`
	WorkspaceID         uuid.UUID          `json:"workspace_id"`
	UserID              uuid.UUID          `json:"user_id"`
	SigningPublicKey    []byte             `json:"signing_public_key"`
	EncryptionPublicKey []byte             `json:"encryption_public_key"`
	EncryptedDeviceName []byte             `json:"encrypted_device_name"`
	LastDeviceSeq       int64              `json:"last_device_seq"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	MetadataVersion     int64              `json:"metadata_version"`
}

type KukuSyncDeviceCursor struct {
	WorkspaceID                uuid.UUID          `json:"workspace_id"`
	DeviceID                   uuid.UUID          `json:"device_id"`
	LastSeenCommitID           pgtype.Text        `json:"last_seen_commit_id"`
	LastSeenCheckpointCommitID pgtype.Text        `json:"last_seen_checkpoint_commit_id"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type KukuSyncKeyEnvelope struct {
	WorkspaceID       uuid.UUID                `json:"workspace_id"`
	EnvelopeID        string                   `json:"envelope_id"`
	RecipientType     KukuSyncKeyRecipientType `json:"recipient_type"`
	RecipientDeviceID uuid.NullUUID            `json:"recipient_device_id"`
	KeyVersion        int64                    `json:"key_version"`
	KdfParams         []byte                   `json:"kdf_params"`
	EncryptedEnvelope []byte                   `json:"encrypted_envelope"`
	CreatedByDeviceID uuid.NullUUID            `json:"created_by_device_id"`
	CreatedAt         pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz       `json:"updated_at"`
}

type KukuSyncObject struct {
	WorkspaceID       uuid.UUID                     `json:"workspace_id"`
	ObjectID          string                        `json:"object_id"`
	ObjectKind        KukuSyncObjectKind            `json:"object_kind"`
	StorageProvider   KukuSyncStorageProvider       `json:"storage_provider"`
	StorageKey        string                        `json:"storage_key"`
	CiphertextSha256  string                        `json:"ciphertext_sha256"`
	SizeBytes         int64                         `json:"size_bytes"`
	UploadState       KukuSyncObjectState           `json:"upload_state"`
	ErrorReason       NullKukuSyncObjectErrorReason `json:"error_reason"`
	CreatedByDeviceID uuid.NullUUID                 `json:"created_by_device_id"`
	CreatedAt         pgtype.Timestamptz            `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz            `json:"updated_at"`
	AvailableAt       pgtype.Timestamptz            `json:"available_at"`
	ExpiresAt         pgtype.Timestamptz            `json:"expires_at"`
	DeletedAt         pgtype.Timestamptz            `json:"deleted_at"`
}

type KukuSyncUsageAccount struct {
	UserID             uuid.UUID          `json:"user_id"`
	WorkspaceCount     int32              `json:"workspace_count"`
	TotalStorageBytes  int64              `json:"total_storage_bytes"`
	PendingUploadBytes int64              `json:"pending_upload_bytes"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KukuSyncUsageWorkspace struct {
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	StorageBytes       int64              `json:"storage_bytes"`
	ObjectCount        int64              `json:"object_count"`
	PendingUploadBytes int64              `json:"pending_upload_bytes"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type KukuSyncWorkspace struct {
	ID                    uuid.UUID          `json:"id"`
	OwnerUserID           uuid.UUID          `json:"owner_user_id"`
	CurrentHeadCommitID   pgtype.Text        `json:"current_head_commit_id"`
	HeadVersion           int64              `json:"head_version"`
	CryptoVersion         string             `json:"crypto_version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	EncryptedMetadata     []byte             `json:"encrypted_metadata"`
	MetadataVersion       int64              `json:"metadata_version"`
	EncryptedWorkspaceKey []byte             `json:"encrypted_workspace_key"`
	WorkspaceKeyVersion   int64              `json:"workspace_key_version"`
}

type KukuUsageStat struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Date       pgtype.Date        `json:"date"`
	AiRequests int32              `json:"ai_requests"`
	TokensK    pgtype.Numeric     `json:"tokens_k"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
