// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Atomic lookup-and-invalidate. The previous separate SELECT + UPDATE pair
	// allowed two concurrent requests with the same code to both pass the
	// IS NULL guard before either UPDATE landed; this single UPDATE is
	// serialized by the row lock, and the RETURNING clause means only the
	// winner gets a non-empty result. A second caller (or a stale/used token)
	// gets pgx.ErrNoRows.
	ConsumeOneTimeToken(ctx context.Context, tokenHash string) (AuthOneTimeToken, error)
	CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error
	CreateFlowState(ctx context.Context, arg CreateFlowStateParams) (AuthFlowState, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error)
	CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) (AuthOneTimeToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	DeleteFlowState(ctx context.Context, id uuid.UUID) error
	EnsureSubscriptionExists(ctx context.Context, userID uuid.UUID) (KukuSubscription, error)
	GetCurrentPeriodUsage(ctx context.Context, arg GetCurrentPeriodUsageParams) (GetCurrentPeriodUsageRow, error)
	GetFlowStateByCode(ctx context.Context, authCode string) (AuthFlowState, error)
	GetIdentityByProviderID(ctx context.Context, arg GetIdentityByProviderIDParams) (AuthIdentity, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error)
	GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (KukuSubscription, error)
	// Explicit column list so the tokens_k cast pins sqlc's generated Go type
	// (float32) regardless of the storage type. Storage is NUMERIC so SUM
	// aggregates are exact; the cast here is lossless for display (REAL has
	// more than enough precision for per-day token counts).
	GetUsageStatsByUserAndDateRange(ctx context.Context, arg GetUsageStatsByUserAndDateRangeParams) ([]GetUsageStatsByUserAndDateRangeRow, error)
	GetUserByEmail(ctx context.Context, email string) (AuthUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	GetValidSession(ctx context.Context, arg GetValidSessionParams) (AuthSession, error)
	InvalidateOneTimeTokensByEmail(ctx context.Context, arg InvalidateOneTimeTokensByEmailParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionRefreshTokens(ctx context.Context, sessionID uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateIdentityLastSignIn(ctx context.Context, arg UpdateIdentityLastSignInParams) error
	UpdateSessionRefreshedAt(ctx context.Context, id uuid.UUID) error
	UpdateUserLastSignIn(ctx context.Context, id uuid.UUID) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (AuthUser, error)
}

var _ Querier = (*Queries)(nil)
