// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddSyncUsageAccountAvailableObjectBytes(ctx context.Context, arg AddSyncUsageAccountAvailableObjectBytesParams) error
	AddSyncUsageAccountPendingBytes(ctx context.Context, arg AddSyncUsageAccountPendingBytesParams) error
	AddSyncUsageAvailableObjectBytes(ctx context.Context, arg AddSyncUsageAvailableObjectBytesParams) error
	AddSyncUsagePendingBytes(ctx context.Context, arg AddSyncUsagePendingBytesParams) error
	CompleteSyncUsageAccountObjectBytes(ctx context.Context, arg CompleteSyncUsageAccountObjectBytesParams) error
	CompleteSyncUsageObjectBytes(ctx context.Context, arg CompleteSyncUsageObjectBytesParams) error
	// Atomic lookup-and-invalidate. The previous separate SELECT + UPDATE pair
	// allowed two concurrent requests with the same code to both pass the
	// IS NULL guard before either UPDATE landed; this single UPDATE is
	// serialized by the row lock, and the RETURNING clause means only the
	// winner gets a non-empty result. A second caller (or a stale/used token)
	// gets pgx.ErrNoRows.
	ConsumeOneTimeToken(ctx context.Context, tokenHash string) (AuthOneTimeToken, error)
	ConsumeRefreshTokenByHash(ctx context.Context, arg ConsumeRefreshTokenByHashParams) (AuthRefreshToken, error)
	CountActiveSyncWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) (int32, error)
	CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error
	CreateFlowState(ctx context.Context, arg CreateFlowStateParams) (AuthFlowState, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error)
	CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) (AuthOneTimeToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error)
	CreateReservedSyncObject(ctx context.Context, arg CreateReservedSyncObjectParams) (KukuSyncObject, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error)
	CreateSyncAccountKey(ctx context.Context, arg CreateSyncAccountKeyParams) (KukuSyncAccountKey, error)
	CreateSyncCommit(ctx context.Context, arg CreateSyncCommitParams) (KukuSyncCommit, error)
	CreateSyncCommitObject(ctx context.Context, arg CreateSyncCommitObjectParams) error
	CreateSyncDevice(ctx context.Context, arg CreateSyncDeviceParams) (KukuSyncDevice, error)
	CreateSyncUsageWorkspace(ctx context.Context, workspaceID uuid.UUID) (KukuSyncUsageWorkspace, error)
	CreateSyncWorkspace(ctx context.Context, arg CreateSyncWorkspaceParams) (KukuSyncWorkspace, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	DeleteFlowState(ctx context.Context, id uuid.UUID) error
	EnsureSubscriptionExists(ctx context.Context, userID uuid.UUID) (KukuSubscription, error)
	EnsureSyncUsageAccount(ctx context.Context, userID uuid.UUID) (KukuSyncUsageAccount, error)
	GetActiveSyncDevice(ctx context.Context, arg GetActiveSyncDeviceParams) (KukuSyncDevice, error)
	GetActiveSyncDeviceForUpdate(ctx context.Context, arg GetActiveSyncDeviceForUpdateParams) (KukuSyncDevice, error)
	GetCurrentPeriodUsage(ctx context.Context, arg GetCurrentPeriodUsageParams) (GetCurrentPeriodUsageRow, error)
	GetFlowStateByCode(ctx context.Context, authCode string) (AuthFlowState, error)
	GetIdentityByProviderID(ctx context.Context, arg GetIdentityByProviderIDParams) (AuthIdentity, error)
	GetLatestSyncCheckpointCommit(ctx context.Context, workspaceID uuid.UUID) (KukuSyncCommit, error)
	GetLatestSyncCheckpointCommitID(ctx context.Context, workspaceID uuid.UUID) (string, error)
	GetSubscriptionByUserID(ctx context.Context, userID uuid.UUID) (KukuSubscription, error)
	GetSubscriptionByUserIDForUpdate(ctx context.Context, userID uuid.UUID) (KukuSubscription, error)
	GetSyncAccountKeyByUser(ctx context.Context, userID uuid.UUID) (KukuSyncAccountKey, error)
	GetSyncCommit(ctx context.Context, arg GetSyncCommitParams) (KukuSyncCommit, error)
	GetSyncObject(ctx context.Context, arg GetSyncObjectParams) (KukuSyncObject, error)
	GetSyncObjectForUpdate(ctx context.Context, arg GetSyncObjectForUpdateParams) (KukuSyncObject, error)
	GetSyncUsageAccountForUpdate(ctx context.Context, userID uuid.UUID) (KukuSyncUsageAccount, error)
	GetSyncUsageWorkspaceForUpdate(ctx context.Context, workspaceID uuid.UUID) (KukuSyncUsageWorkspace, error)
	GetSyncWorkspaceByIDAndOwner(ctx context.Context, arg GetSyncWorkspaceByIDAndOwnerParams) (KukuSyncWorkspace, error)
	GetSyncWorkspaceForUpdate(ctx context.Context, arg GetSyncWorkspaceForUpdateParams) (KukuSyncWorkspace, error)
	// Explicit column list so the tokens_k cast pins sqlc's generated Go type
	// (float32) regardless of the storage type. Storage is NUMERIC so SUM
	// aggregates are exact; the cast here is lossless for display (REAL has
	// more than enough precision for per-day token counts).
	GetUsageStatsByUserAndDateRange(ctx context.Context, arg GetUsageStatsByUserAndDateRangeParams) ([]GetUsageStatsByUserAndDateRangeRow, error)
	GetUserByEmail(ctx context.Context, email string) (AuthUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	GetValidSession(ctx context.Context, arg GetValidSessionParams) (AuthSession, error)
	HardDeleteSyncWorkspace(ctx context.Context, id uuid.UUID) error
	IncrementDailyAIRequests(ctx context.Context, arg IncrementDailyAIRequestsParams) error
	IncrementDailyAITokens(ctx context.Context, arg IncrementDailyAITokensParams) error
	IncrementSyncUsageWorkspaceCount(ctx context.Context, arg IncrementSyncUsageWorkspaceCountParams) error
	InvalidateOneTimeTokensByEmail(ctx context.Context, arg InvalidateOneTimeTokensByEmailParams) error
	ListAllSyncObjectsByWorkspaceForUpdate(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncObject, error)
	ListDeletedSyncWorkspacesForCleanup(ctx context.Context, arg ListDeletedSyncWorkspacesForCleanupParams) ([]KukuSyncWorkspace, error)
	ListExpiredOrphanSyncObjectsForUpdate(ctx context.Context, arg ListExpiredOrphanSyncObjectsForUpdateParams) ([]KukuSyncObject, error)
	ListSyncAccountKeyEnvelopes(ctx context.Context, userID uuid.UUID) ([]KukuSyncAccountKeyEnvelope, error)
	ListSyncCommitObjectsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncCommitObject, error)
	ListSyncCommitsAfterServerSeq(ctx context.Context, arg ListSyncCommitsAfterServerSeqParams) ([]KukuSyncCommit, error)
	ListSyncCommitsByWorkspaceDesc(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncCommit, error)
	ListSyncKeyEnvelopes(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncKeyEnvelope, error)
	ListSyncObjectsByIDs(ctx context.Context, arg ListSyncObjectsByIDsParams) ([]KukuSyncObject, error)
	ListSyncWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]KukuSyncWorkspace, error)
	MarkSyncObjectAvailable(ctx context.Context, arg MarkSyncObjectAvailableParams) (KukuSyncObject, error)
	MarkSyncObjectDeleted(ctx context.Context, arg MarkSyncObjectDeletedParams) (KukuSyncObject, error)
	MarkSyncObjectFailed(ctx context.Context, arg MarkSyncObjectFailedParams) (KukuSyncObject, error)
	MarkSyncObjectPending(ctx context.Context, arg MarkSyncObjectPendingParams) (KukuSyncObject, error)
	MarkSyncObjectsDeletedByOwner(ctx context.Context, ownerUserID uuid.UUID) error
	RecalculateSyncUsageAccount(ctx context.Context, userID uuid.UUID) (KukuSyncUsageAccount, error)
	RecalculateSyncUsageWorkspace(ctx context.Context, workspaceID uuid.UUID) (KukuSyncUsageWorkspace, error)
	ReleaseSyncUsageAccountPendingBytes(ctx context.Context, arg ReleaseSyncUsageAccountPendingBytesParams) error
	ReleaseSyncUsagePendingBytes(ctx context.Context, arg ReleaseSyncUsagePendingBytesParams) error
	ResetSyncUsageAccount(ctx context.Context, userID uuid.UUID) error
	ResetSyncUsageWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionRefreshTokens(ctx context.Context, sessionID uuid.UUID) error
	RevokeSyncDevicesByOwner(ctx context.Context, ownerUserID uuid.UUID) error
	SoftDeleteSyncWorkspace(ctx context.Context, arg SoftDeleteSyncWorkspaceParams) error
	SoftDeleteSyncWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	TouchSyncDeviceLastSeen(ctx context.Context, arg TouchSyncDeviceLastSeenParams) error
	UpdateIdentityLastSignIn(ctx context.Context, arg UpdateIdentityLastSignInParams) error
	UpdateSessionRefreshedAt(ctx context.Context, id uuid.UUID) error
	UpdateSubscriptionPeriod(ctx context.Context, arg UpdateSubscriptionPeriodParams) (KukuSubscription, error)
	UpdateSyncDeviceMetadata(ctx context.Context, arg UpdateSyncDeviceMetadataParams) (KukuSyncDevice, error)
	UpdateSyncDeviceSequence(ctx context.Context, arg UpdateSyncDeviceSequenceParams) error
	UpdateSyncWorkspaceHead(ctx context.Context, arg UpdateSyncWorkspaceHeadParams) (KukuSyncWorkspace, error)
	UpdateSyncWorkspaceKey(ctx context.Context, arg UpdateSyncWorkspaceKeyParams) (KukuSyncWorkspace, error)
	UpdateSyncWorkspaceMetadata(ctx context.Context, arg UpdateSyncWorkspaceMetadataParams) (KukuSyncWorkspace, error)
	UpdateUserLastSignIn(ctx context.Context, id uuid.UUID) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (AuthUser, error)
	UpsertSyncAccountKeyEnvelope(ctx context.Context, arg UpsertSyncAccountKeyEnvelopeParams) (KukuSyncAccountKeyEnvelope, error)
	UpsertSyncDeviceCursor(ctx context.Context, arg UpsertSyncDeviceCursorParams) error
	UpsertSyncKeyEnvelope(ctx context.Context, arg UpsertSyncKeyEnvelopeParams) (KukuSyncKeyEnvelope, error)
}

var _ Querier = (*Queries)(nil)
