// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSyncUsageAccountAvailableObjectBytes = `-- name: AddSyncUsageAccountAvailableObjectBytes :exec
UPDATE kuku.sync_usage_accounts
SET total_storage_bytes = total_storage_bytes + $2,
    updated_at = now()
WHERE user_id = $1
`

type AddSyncUsageAccountAvailableObjectBytesParams struct {
	UserID            uuid.UUID `json:"user_id"`
	TotalStorageBytes int64     `json:"total_storage_bytes"`
}

func (q *Queries) AddSyncUsageAccountAvailableObjectBytes(ctx context.Context, arg AddSyncUsageAccountAvailableObjectBytesParams) error {
	_, err := q.db.Exec(ctx, addSyncUsageAccountAvailableObjectBytes, arg.UserID, arg.TotalStorageBytes)
	return err
}

const addSyncUsageAccountPendingBytes = `-- name: AddSyncUsageAccountPendingBytes :exec
UPDATE kuku.sync_usage_accounts
SET pending_upload_bytes = pending_upload_bytes + $2,
    updated_at = now()
WHERE user_id = $1
`

type AddSyncUsageAccountPendingBytesParams struct {
	UserID             uuid.UUID `json:"user_id"`
	PendingUploadBytes int64     `json:"pending_upload_bytes"`
}

func (q *Queries) AddSyncUsageAccountPendingBytes(ctx context.Context, arg AddSyncUsageAccountPendingBytesParams) error {
	_, err := q.db.Exec(ctx, addSyncUsageAccountPendingBytes, arg.UserID, arg.PendingUploadBytes)
	return err
}

const addSyncUsageAvailableObjectBytes = `-- name: AddSyncUsageAvailableObjectBytes :exec
UPDATE kuku.sync_usage_workspaces
SET storage_bytes = storage_bytes + $2,
    object_count = object_count + 1,
    updated_at = now()
WHERE workspace_id = $1
`

type AddSyncUsageAvailableObjectBytesParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	StorageBytes int64     `json:"storage_bytes"`
}

func (q *Queries) AddSyncUsageAvailableObjectBytes(ctx context.Context, arg AddSyncUsageAvailableObjectBytesParams) error {
	_, err := q.db.Exec(ctx, addSyncUsageAvailableObjectBytes, arg.WorkspaceID, arg.StorageBytes)
	return err
}

const addSyncUsagePendingBytes = `-- name: AddSyncUsagePendingBytes :exec
UPDATE kuku.sync_usage_workspaces
SET pending_upload_bytes = pending_upload_bytes + $2,
    updated_at = now()
WHERE workspace_id = $1
`

type AddSyncUsagePendingBytesParams struct {
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	PendingUploadBytes int64     `json:"pending_upload_bytes"`
}

func (q *Queries) AddSyncUsagePendingBytes(ctx context.Context, arg AddSyncUsagePendingBytesParams) error {
	_, err := q.db.Exec(ctx, addSyncUsagePendingBytes, arg.WorkspaceID, arg.PendingUploadBytes)
	return err
}

const completeSyncUsageAccountObjectBytes = `-- name: CompleteSyncUsageAccountObjectBytes :exec
UPDATE kuku.sync_usage_accounts
SET pending_upload_bytes = pending_upload_bytes - $2,
    total_storage_bytes = total_storage_bytes + $2,
    updated_at = now()
WHERE user_id = $1
`

type CompleteSyncUsageAccountObjectBytesParams struct {
	UserID             uuid.UUID `json:"user_id"`
	PendingUploadBytes int64     `json:"pending_upload_bytes"`
}

func (q *Queries) CompleteSyncUsageAccountObjectBytes(ctx context.Context, arg CompleteSyncUsageAccountObjectBytesParams) error {
	_, err := q.db.Exec(ctx, completeSyncUsageAccountObjectBytes, arg.UserID, arg.PendingUploadBytes)
	return err
}

const completeSyncUsageObjectBytes = `-- name: CompleteSyncUsageObjectBytes :exec
UPDATE kuku.sync_usage_workspaces
SET pending_upload_bytes = pending_upload_bytes - $2,
    storage_bytes = storage_bytes + $2,
    object_count = object_count + 1,
    updated_at = now()
WHERE workspace_id = $1
`

type CompleteSyncUsageObjectBytesParams struct {
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	PendingUploadBytes int64     `json:"pending_upload_bytes"`
}

func (q *Queries) CompleteSyncUsageObjectBytes(ctx context.Context, arg CompleteSyncUsageObjectBytesParams) error {
	_, err := q.db.Exec(ctx, completeSyncUsageObjectBytes, arg.WorkspaceID, arg.PendingUploadBytes)
	return err
}

const countActiveSyncWorkspacesByOwner = `-- name: CountActiveSyncWorkspacesByOwner :one
SELECT count(*)::INTEGER FROM kuku.sync_workspaces
WHERE owner_user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountActiveSyncWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSyncWorkspacesByOwner, ownerUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createReservedSyncObject = `-- name: CreateReservedSyncObject :one
INSERT INTO kuku.sync_objects (
  workspace_id,
  object_id,
  object_kind,
  storage_provider,
  storage_key,
  upload_state,
  created_by_device_id,
  expires_at
)
VALUES ($1, $2, $3, $4, $5, 'reserved', $6, $7)
RETURNING workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at
`

type CreateReservedSyncObjectParams struct {
	WorkspaceID       uuid.UUID               `json:"workspace_id"`
	ObjectID          string                  `json:"object_id"`
	ObjectKind        KukuSyncObjectKind      `json:"object_kind"`
	StorageProvider   KukuSyncStorageProvider `json:"storage_provider"`
	StorageKey        string                  `json:"storage_key"`
	CreatedByDeviceID uuid.NullUUID           `json:"created_by_device_id"`
	ExpiresAt         pgtype.Timestamptz      `json:"expires_at"`
}

func (q *Queries) CreateReservedSyncObject(ctx context.Context, arg CreateReservedSyncObjectParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, createReservedSyncObject,
		arg.WorkspaceID,
		arg.ObjectID,
		arg.ObjectKind,
		arg.StorageProvider,
		arg.StorageKey,
		arg.CreatedByDeviceID,
		arg.ExpiresAt,
	)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSyncAccountKey = `-- name: CreateSyncAccountKey :one
INSERT INTO kuku.sync_account_keys (
  user_id,
  account_key_id,
  crypto_version
)
VALUES ($1, $2, $3)
RETURNING user_id, account_key_id, crypto_version, created_at, updated_at
`

type CreateSyncAccountKeyParams struct {
	UserID        uuid.UUID `json:"user_id"`
	AccountKeyID  string    `json:"account_key_id"`
	CryptoVersion string    `json:"crypto_version"`
}

func (q *Queries) CreateSyncAccountKey(ctx context.Context, arg CreateSyncAccountKeyParams) (KukuSyncAccountKey, error) {
	row := q.db.QueryRow(ctx, createSyncAccountKey, arg.UserID, arg.AccountKeyID, arg.CryptoVersion)
	var i KukuSyncAccountKey
	err := row.Scan(
		&i.UserID,
		&i.AccountKeyID,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncCommit = `-- name: CreateSyncCommit :one
INSERT INTO kuku.sync_commits (
  workspace_id,
  commit_id,
  commit_kind,
  expected_head_commit_id,
  author_device_id,
  device_seq,
  parent_commit_ids,
  body_object_id,
  body_ciphertext_sha256,
  body_size_bytes,
  referenced_object_ids,
  signature
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING workspace_id, commit_id, commit_kind, author_device_id, device_seq, parent_commit_ids, body_object_id, body_ciphertext_sha256, body_size_bytes, referenced_object_ids, signature, server_seq, created_at, expected_head_commit_id
`

type CreateSyncCommitParams struct {
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	CommitID             string             `json:"commit_id"`
	CommitKind           KukuSyncCommitKind `json:"commit_kind"`
	ExpectedHeadCommitID pgtype.Text        `json:"expected_head_commit_id"`
	AuthorDeviceID       uuid.UUID          `json:"author_device_id"`
	DeviceSeq            int64              `json:"device_seq"`
	ParentCommitIds      []string           `json:"parent_commit_ids"`
	BodyObjectID         string             `json:"body_object_id"`
	BodyCiphertextSha256 string             `json:"body_ciphertext_sha256"`
	BodySizeBytes        int64              `json:"body_size_bytes"`
	ReferencedObjectIds  []string           `json:"referenced_object_ids"`
	Signature            []byte             `json:"signature"`
}

func (q *Queries) CreateSyncCommit(ctx context.Context, arg CreateSyncCommitParams) (KukuSyncCommit, error) {
	row := q.db.QueryRow(ctx, createSyncCommit,
		arg.WorkspaceID,
		arg.CommitID,
		arg.CommitKind,
		arg.ExpectedHeadCommitID,
		arg.AuthorDeviceID,
		arg.DeviceSeq,
		arg.ParentCommitIds,
		arg.BodyObjectID,
		arg.BodyCiphertextSha256,
		arg.BodySizeBytes,
		arg.ReferencedObjectIds,
		arg.Signature,
	)
	var i KukuSyncCommit
	err := row.Scan(
		&i.WorkspaceID,
		&i.CommitID,
		&i.CommitKind,
		&i.AuthorDeviceID,
		&i.DeviceSeq,
		&i.ParentCommitIds,
		&i.BodyObjectID,
		&i.BodyCiphertextSha256,
		&i.BodySizeBytes,
		&i.ReferencedObjectIds,
		&i.Signature,
		&i.ServerSeq,
		&i.CreatedAt,
		&i.ExpectedHeadCommitID,
	)
	return i, err
}

const createSyncCommitObject = `-- name: CreateSyncCommitObject :exec
INSERT INTO kuku.sync_commit_objects (workspace_id, commit_id, object_id, object_role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, commit_id, object_id) DO NOTHING
`

type CreateSyncCommitObjectParams struct {
	WorkspaceID uuid.UUID                `json:"workspace_id"`
	CommitID    string                   `json:"commit_id"`
	ObjectID    string                   `json:"object_id"`
	ObjectRole  KukuSyncCommitObjectRole `json:"object_role"`
}

func (q *Queries) CreateSyncCommitObject(ctx context.Context, arg CreateSyncCommitObjectParams) error {
	_, err := q.db.Exec(ctx, createSyncCommitObject,
		arg.WorkspaceID,
		arg.CommitID,
		arg.ObjectID,
		arg.ObjectRole,
	)
	return err
}

const createSyncDevice = `-- name: CreateSyncDevice :one
INSERT INTO kuku.sync_devices (
  workspace_id,
  user_id,
  signing_public_key,
  encryption_public_key,
  encrypted_device_name,
  last_seen_at
)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, workspace_id, user_id, signing_public_key, encryption_public_key, encrypted_device_name, last_device_seq, created_at, updated_at, last_seen_at, revoked_at, metadata_version
`

type CreateSyncDeviceParams struct {
	WorkspaceID         uuid.UUID `json:"workspace_id"`
	UserID              uuid.UUID `json:"user_id"`
	SigningPublicKey    []byte    `json:"signing_public_key"`
	EncryptionPublicKey []byte    `json:"encryption_public_key"`
	EncryptedDeviceName []byte    `json:"encrypted_device_name"`
}

func (q *Queries) CreateSyncDevice(ctx context.Context, arg CreateSyncDeviceParams) (KukuSyncDevice, error) {
	row := q.db.QueryRow(ctx, createSyncDevice,
		arg.WorkspaceID,
		arg.UserID,
		arg.SigningPublicKey,
		arg.EncryptionPublicKey,
		arg.EncryptedDeviceName,
	)
	var i KukuSyncDevice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SigningPublicKey,
		&i.EncryptionPublicKey,
		&i.EncryptedDeviceName,
		&i.LastDeviceSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.MetadataVersion,
	)
	return i, err
}

const createSyncUsageWorkspace = `-- name: CreateSyncUsageWorkspace :one
INSERT INTO kuku.sync_usage_workspaces (workspace_id)
VALUES ($1)
RETURNING workspace_id, storage_bytes, object_count, pending_upload_bytes, updated_at
`

func (q *Queries) CreateSyncUsageWorkspace(ctx context.Context, workspaceID uuid.UUID) (KukuSyncUsageWorkspace, error) {
	row := q.db.QueryRow(ctx, createSyncUsageWorkspace, workspaceID)
	var i KukuSyncUsageWorkspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.StorageBytes,
		&i.ObjectCount,
		&i.PendingUploadBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const createSyncWorkspace = `-- name: CreateSyncWorkspace :one
INSERT INTO kuku.sync_workspaces (owner_user_id, crypto_version)
VALUES ($1, $2)
RETURNING id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version
`

type CreateSyncWorkspaceParams struct {
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	CryptoVersion string    `json:"crypto_version"`
}

func (q *Queries) CreateSyncWorkspace(ctx context.Context, arg CreateSyncWorkspaceParams) (KukuSyncWorkspace, error) {
	row := q.db.QueryRow(ctx, createSyncWorkspace, arg.OwnerUserID, arg.CryptoVersion)
	var i KukuSyncWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.CurrentHeadCommitID,
		&i.HeadVersion,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EncryptedMetadata,
		&i.MetadataVersion,
		&i.EncryptedWorkspaceKey,
		&i.WorkspaceKeyVersion,
	)
	return i, err
}

const ensureSyncUsageAccount = `-- name: EnsureSyncUsageAccount :one
INSERT INTO kuku.sync_usage_accounts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = now()
RETURNING user_id, workspace_count, total_storage_bytes, pending_upload_bytes, updated_at
`

func (q *Queries) EnsureSyncUsageAccount(ctx context.Context, userID uuid.UUID) (KukuSyncUsageAccount, error) {
	row := q.db.QueryRow(ctx, ensureSyncUsageAccount, userID)
	var i KukuSyncUsageAccount
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceCount,
		&i.TotalStorageBytes,
		&i.PendingUploadBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSyncDevice = `-- name: GetActiveSyncDevice :one
SELECT id, workspace_id, user_id, signing_public_key, encryption_public_key, encrypted_device_name, last_device_seq, created_at, updated_at, last_seen_at, revoked_at, metadata_version FROM kuku.sync_devices
WHERE workspace_id = $1
  AND id = $2
  AND user_id = $3
  AND revoked_at IS NULL
`

type GetActiveSyncDeviceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveSyncDevice(ctx context.Context, arg GetActiveSyncDeviceParams) (KukuSyncDevice, error) {
	row := q.db.QueryRow(ctx, getActiveSyncDevice, arg.WorkspaceID, arg.ID, arg.UserID)
	var i KukuSyncDevice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SigningPublicKey,
		&i.EncryptionPublicKey,
		&i.EncryptedDeviceName,
		&i.LastDeviceSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.MetadataVersion,
	)
	return i, err
}

const getActiveSyncDeviceForUpdate = `-- name: GetActiveSyncDeviceForUpdate :one
SELECT id, workspace_id, user_id, signing_public_key, encryption_public_key, encrypted_device_name, last_device_seq, created_at, updated_at, last_seen_at, revoked_at, metadata_version FROM kuku.sync_devices
WHERE workspace_id = $1
  AND id = $2
  AND user_id = $3
  AND revoked_at IS NULL
FOR UPDATE
`

type GetActiveSyncDeviceForUpdateParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveSyncDeviceForUpdate(ctx context.Context, arg GetActiveSyncDeviceForUpdateParams) (KukuSyncDevice, error) {
	row := q.db.QueryRow(ctx, getActiveSyncDeviceForUpdate, arg.WorkspaceID, arg.ID, arg.UserID)
	var i KukuSyncDevice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SigningPublicKey,
		&i.EncryptionPublicKey,
		&i.EncryptedDeviceName,
		&i.LastDeviceSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.MetadataVersion,
	)
	return i, err
}

const getLatestSyncCheckpointCommit = `-- name: GetLatestSyncCheckpointCommit :one
SELECT workspace_id, commit_id, commit_kind, author_device_id, device_seq, parent_commit_ids, body_object_id, body_ciphertext_sha256, body_size_bytes, referenced_object_ids, signature, server_seq, created_at, expected_head_commit_id FROM kuku.sync_commits
WHERE workspace_id = $1
  AND commit_kind = 'checkpoint'
ORDER BY server_seq DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncCheckpointCommit(ctx context.Context, workspaceID uuid.UUID) (KukuSyncCommit, error) {
	row := q.db.QueryRow(ctx, getLatestSyncCheckpointCommit, workspaceID)
	var i KukuSyncCommit
	err := row.Scan(
		&i.WorkspaceID,
		&i.CommitID,
		&i.CommitKind,
		&i.AuthorDeviceID,
		&i.DeviceSeq,
		&i.ParentCommitIds,
		&i.BodyObjectID,
		&i.BodyCiphertextSha256,
		&i.BodySizeBytes,
		&i.ReferencedObjectIds,
		&i.Signature,
		&i.ServerSeq,
		&i.CreatedAt,
		&i.ExpectedHeadCommitID,
	)
	return i, err
}

const getLatestSyncCheckpointCommitID = `-- name: GetLatestSyncCheckpointCommitID :one
SELECT commit_id FROM kuku.sync_commits
WHERE workspace_id = $1
  AND commit_kind = 'checkpoint'
ORDER BY server_seq DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncCheckpointCommitID(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestSyncCheckpointCommitID, workspaceID)
	var commit_id string
	err := row.Scan(&commit_id)
	return commit_id, err
}

const getSyncAccountKeyByUser = `-- name: GetSyncAccountKeyByUser :one
SELECT user_id, account_key_id, crypto_version, created_at, updated_at FROM kuku.sync_account_keys
WHERE user_id = $1
`

func (q *Queries) GetSyncAccountKeyByUser(ctx context.Context, userID uuid.UUID) (KukuSyncAccountKey, error) {
	row := q.db.QueryRow(ctx, getSyncAccountKeyByUser, userID)
	var i KukuSyncAccountKey
	err := row.Scan(
		&i.UserID,
		&i.AccountKeyID,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncCommit = `-- name: GetSyncCommit :one
SELECT workspace_id, commit_id, commit_kind, author_device_id, device_seq, parent_commit_ids, body_object_id, body_ciphertext_sha256, body_size_bytes, referenced_object_ids, signature, server_seq, created_at, expected_head_commit_id FROM kuku.sync_commits
WHERE workspace_id = $1
  AND commit_id = $2
`

type GetSyncCommitParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	CommitID    string    `json:"commit_id"`
}

func (q *Queries) GetSyncCommit(ctx context.Context, arg GetSyncCommitParams) (KukuSyncCommit, error) {
	row := q.db.QueryRow(ctx, getSyncCommit, arg.WorkspaceID, arg.CommitID)
	var i KukuSyncCommit
	err := row.Scan(
		&i.WorkspaceID,
		&i.CommitID,
		&i.CommitKind,
		&i.AuthorDeviceID,
		&i.DeviceSeq,
		&i.ParentCommitIds,
		&i.BodyObjectID,
		&i.BodyCiphertextSha256,
		&i.BodySizeBytes,
		&i.ReferencedObjectIds,
		&i.Signature,
		&i.ServerSeq,
		&i.CreatedAt,
		&i.ExpectedHeadCommitID,
	)
	return i, err
}

const getSyncObject = `-- name: GetSyncObject :one
SELECT workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at FROM kuku.sync_objects
WHERE workspace_id = $1
  AND object_id = $2
  AND deleted_at IS NULL
`

type GetSyncObjectParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ObjectID    string    `json:"object_id"`
}

func (q *Queries) GetSyncObject(ctx context.Context, arg GetSyncObjectParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, getSyncObject, arg.WorkspaceID, arg.ObjectID)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSyncObjectForUpdate = `-- name: GetSyncObjectForUpdate :one
SELECT workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at FROM kuku.sync_objects
WHERE workspace_id = $1
  AND object_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type GetSyncObjectForUpdateParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ObjectID    string    `json:"object_id"`
}

func (q *Queries) GetSyncObjectForUpdate(ctx context.Context, arg GetSyncObjectForUpdateParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, getSyncObjectForUpdate, arg.WorkspaceID, arg.ObjectID)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSyncUsageAccountForUpdate = `-- name: GetSyncUsageAccountForUpdate :one
SELECT user_id, workspace_count, total_storage_bytes, pending_upload_bytes, updated_at FROM kuku.sync_usage_accounts
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetSyncUsageAccountForUpdate(ctx context.Context, userID uuid.UUID) (KukuSyncUsageAccount, error) {
	row := q.db.QueryRow(ctx, getSyncUsageAccountForUpdate, userID)
	var i KukuSyncUsageAccount
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceCount,
		&i.TotalStorageBytes,
		&i.PendingUploadBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncUsageWorkspaceForUpdate = `-- name: GetSyncUsageWorkspaceForUpdate :one
SELECT workspace_id, storage_bytes, object_count, pending_upload_bytes, updated_at FROM kuku.sync_usage_workspaces
WHERE workspace_id = $1
FOR UPDATE
`

func (q *Queries) GetSyncUsageWorkspaceForUpdate(ctx context.Context, workspaceID uuid.UUID) (KukuSyncUsageWorkspace, error) {
	row := q.db.QueryRow(ctx, getSyncUsageWorkspaceForUpdate, workspaceID)
	var i KukuSyncUsageWorkspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.StorageBytes,
		&i.ObjectCount,
		&i.PendingUploadBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncWorkspaceByIDAndOwner = `-- name: GetSyncWorkspaceByIDAndOwner :one
SELECT id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version FROM kuku.sync_workspaces
WHERE id = $1
  AND owner_user_id = $2
  AND deleted_at IS NULL
`

type GetSyncWorkspaceByIDAndOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetSyncWorkspaceByIDAndOwner(ctx context.Context, arg GetSyncWorkspaceByIDAndOwnerParams) (KukuSyncWorkspace, error) {
	row := q.db.QueryRow(ctx, getSyncWorkspaceByIDAndOwner, arg.ID, arg.OwnerUserID)
	var i KukuSyncWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.CurrentHeadCommitID,
		&i.HeadVersion,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EncryptedMetadata,
		&i.MetadataVersion,
		&i.EncryptedWorkspaceKey,
		&i.WorkspaceKeyVersion,
	)
	return i, err
}

const getSyncWorkspaceForUpdate = `-- name: GetSyncWorkspaceForUpdate :one
SELECT id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version FROM kuku.sync_workspaces
WHERE id = $1
  AND owner_user_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type GetSyncWorkspaceForUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetSyncWorkspaceForUpdate(ctx context.Context, arg GetSyncWorkspaceForUpdateParams) (KukuSyncWorkspace, error) {
	row := q.db.QueryRow(ctx, getSyncWorkspaceForUpdate, arg.ID, arg.OwnerUserID)
	var i KukuSyncWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.CurrentHeadCommitID,
		&i.HeadVersion,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EncryptedMetadata,
		&i.MetadataVersion,
		&i.EncryptedWorkspaceKey,
		&i.WorkspaceKeyVersion,
	)
	return i, err
}

const hardDeleteSyncWorkspace = `-- name: HardDeleteSyncWorkspace :exec
DELETE FROM kuku.sync_workspaces
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteSyncWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteSyncWorkspace, id)
	return err
}

const incrementSyncUsageWorkspaceCount = `-- name: IncrementSyncUsageWorkspaceCount :exec
UPDATE kuku.sync_usage_accounts
SET workspace_count = workspace_count + $2,
    updated_at = now()
WHERE user_id = $1
`

type IncrementSyncUsageWorkspaceCountParams struct {
	UserID         uuid.UUID `json:"user_id"`
	WorkspaceCount int32     `json:"workspace_count"`
}

func (q *Queries) IncrementSyncUsageWorkspaceCount(ctx context.Context, arg IncrementSyncUsageWorkspaceCountParams) error {
	_, err := q.db.Exec(ctx, incrementSyncUsageWorkspaceCount, arg.UserID, arg.WorkspaceCount)
	return err
}

const listAllSyncObjectsByWorkspaceForUpdate = `-- name: ListAllSyncObjectsByWorkspaceForUpdate :many
SELECT workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at FROM kuku.sync_objects
WHERE workspace_id = $1
ORDER BY object_id ASC
FOR UPDATE
`

func (q *Queries) ListAllSyncObjectsByWorkspaceForUpdate(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncObject, error) {
	rows, err := q.db.Query(ctx, listAllSyncObjectsByWorkspaceForUpdate, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncObject
	for rows.Next() {
		var i KukuSyncObject
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ObjectID,
			&i.ObjectKind,
			&i.StorageProvider,
			&i.StorageKey,
			&i.CiphertextSha256,
			&i.SizeBytes,
			&i.UploadState,
			&i.ErrorReason,
			&i.CreatedByDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedSyncWorkspacesForCleanup = `-- name: ListDeletedSyncWorkspacesForCleanup :many
SELECT id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version FROM kuku.sync_workspaces
WHERE deleted_at IS NOT NULL
  AND deleted_at <= $1
ORDER BY deleted_at ASC, id ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListDeletedSyncWorkspacesForCleanupParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListDeletedSyncWorkspacesForCleanup(ctx context.Context, arg ListDeletedSyncWorkspacesForCleanupParams) ([]KukuSyncWorkspace, error) {
	rows, err := q.db.Query(ctx, listDeletedSyncWorkspacesForCleanup, arg.DeletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncWorkspace
	for rows.Next() {
		var i KukuSyncWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.CurrentHeadCommitID,
			&i.HeadVersion,
			&i.CryptoVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EncryptedMetadata,
			&i.MetadataVersion,
			&i.EncryptedWorkspaceKey,
			&i.WorkspaceKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredOrphanSyncObjectsForUpdate = `-- name: ListExpiredOrphanSyncObjectsForUpdate :many
SELECT workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at FROM kuku.sync_objects
WHERE workspace_id = $1
  AND upload_state IN ('reserved', 'pending', 'failed')
  AND deleted_at IS NULL
  AND expires_at IS NOT NULL
  AND expires_at <= $2
ORDER BY expires_at ASC, object_id ASC
LIMIT $3
FOR UPDATE SKIP LOCKED
`

type ListExpiredOrphanSyncObjectsForUpdateParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListExpiredOrphanSyncObjectsForUpdate(ctx context.Context, arg ListExpiredOrphanSyncObjectsForUpdateParams) ([]KukuSyncObject, error) {
	rows, err := q.db.Query(ctx, listExpiredOrphanSyncObjectsForUpdate, arg.WorkspaceID, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncObject
	for rows.Next() {
		var i KukuSyncObject
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ObjectID,
			&i.ObjectKind,
			&i.StorageProvider,
			&i.StorageKey,
			&i.CiphertextSha256,
			&i.SizeBytes,
			&i.UploadState,
			&i.ErrorReason,
			&i.CreatedByDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncAccountKeyEnvelopes = `-- name: ListSyncAccountKeyEnvelopes :many
SELECT user_id, account_key_id, envelope_id, recipient_type, key_version, kdf_params, encrypted_envelope, created_at, updated_at FROM kuku.sync_account_key_envelopes
WHERE user_id = $1
ORDER BY key_version ASC, envelope_id ASC
`

func (q *Queries) ListSyncAccountKeyEnvelopes(ctx context.Context, userID uuid.UUID) ([]KukuSyncAccountKeyEnvelope, error) {
	rows, err := q.db.Query(ctx, listSyncAccountKeyEnvelopes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncAccountKeyEnvelope
	for rows.Next() {
		var i KukuSyncAccountKeyEnvelope
		if err := rows.Scan(
			&i.UserID,
			&i.AccountKeyID,
			&i.EnvelopeID,
			&i.RecipientType,
			&i.KeyVersion,
			&i.KdfParams,
			&i.EncryptedEnvelope,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCommitObjectsByWorkspace = `-- name: ListSyncCommitObjectsByWorkspace :many
SELECT workspace_id, commit_id, object_id, object_role FROM kuku.sync_commit_objects
WHERE workspace_id = $1
ORDER BY commit_id ASC, object_id ASC
`

func (q *Queries) ListSyncCommitObjectsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncCommitObject, error) {
	rows, err := q.db.Query(ctx, listSyncCommitObjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncCommitObject
	for rows.Next() {
		var i KukuSyncCommitObject
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CommitID,
			&i.ObjectID,
			&i.ObjectRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCommitsAfterServerSeq = `-- name: ListSyncCommitsAfterServerSeq :many
SELECT workspace_id, commit_id, commit_kind, author_device_id, device_seq, parent_commit_ids, body_object_id, body_ciphertext_sha256, body_size_bytes, referenced_object_ids, signature, server_seq, created_at, expected_head_commit_id FROM kuku.sync_commits
WHERE workspace_id = $1
  AND server_seq > $2
ORDER BY server_seq ASC
LIMIT $3
`

type ListSyncCommitsAfterServerSeqParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ServerSeq   pgtype.Int8 `json:"server_seq"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListSyncCommitsAfterServerSeq(ctx context.Context, arg ListSyncCommitsAfterServerSeqParams) ([]KukuSyncCommit, error) {
	rows, err := q.db.Query(ctx, listSyncCommitsAfterServerSeq, arg.WorkspaceID, arg.ServerSeq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncCommit
	for rows.Next() {
		var i KukuSyncCommit
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CommitID,
			&i.CommitKind,
			&i.AuthorDeviceID,
			&i.DeviceSeq,
			&i.ParentCommitIds,
			&i.BodyObjectID,
			&i.BodyCiphertextSha256,
			&i.BodySizeBytes,
			&i.ReferencedObjectIds,
			&i.Signature,
			&i.ServerSeq,
			&i.CreatedAt,
			&i.ExpectedHeadCommitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncCommitsByWorkspaceDesc = `-- name: ListSyncCommitsByWorkspaceDesc :many
SELECT workspace_id, commit_id, commit_kind, author_device_id, device_seq, parent_commit_ids, body_object_id, body_ciphertext_sha256, body_size_bytes, referenced_object_ids, signature, server_seq, created_at, expected_head_commit_id FROM kuku.sync_commits
WHERE workspace_id = $1
ORDER BY server_seq DESC
`

func (q *Queries) ListSyncCommitsByWorkspaceDesc(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncCommit, error) {
	rows, err := q.db.Query(ctx, listSyncCommitsByWorkspaceDesc, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncCommit
	for rows.Next() {
		var i KukuSyncCommit
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CommitID,
			&i.CommitKind,
			&i.AuthorDeviceID,
			&i.DeviceSeq,
			&i.ParentCommitIds,
			&i.BodyObjectID,
			&i.BodyCiphertextSha256,
			&i.BodySizeBytes,
			&i.ReferencedObjectIds,
			&i.Signature,
			&i.ServerSeq,
			&i.CreatedAt,
			&i.ExpectedHeadCommitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncKeyEnvelopes = `-- name: ListSyncKeyEnvelopes :many
SELECT workspace_id, envelope_id, recipient_type, recipient_device_id, key_version, kdf_params, encrypted_envelope, created_by_device_id, created_at, updated_at FROM kuku.sync_key_envelopes
WHERE workspace_id = $1
ORDER BY key_version ASC, envelope_id ASC
`

func (q *Queries) ListSyncKeyEnvelopes(ctx context.Context, workspaceID uuid.UUID) ([]KukuSyncKeyEnvelope, error) {
	rows, err := q.db.Query(ctx, listSyncKeyEnvelopes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncKeyEnvelope
	for rows.Next() {
		var i KukuSyncKeyEnvelope
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.EnvelopeID,
			&i.RecipientType,
			&i.RecipientDeviceID,
			&i.KeyVersion,
			&i.KdfParams,
			&i.EncryptedEnvelope,
			&i.CreatedByDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncObjectsByIDs = `-- name: ListSyncObjectsByIDs :many
SELECT workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at FROM kuku.sync_objects
WHERE workspace_id = $1
  AND object_id = ANY($2::TEXT[])
  AND deleted_at IS NULL
ORDER BY object_id ASC
`

type ListSyncObjectsByIDsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Column2     []string  `json:"column_2"`
}

func (q *Queries) ListSyncObjectsByIDs(ctx context.Context, arg ListSyncObjectsByIDsParams) ([]KukuSyncObject, error) {
	rows, err := q.db.Query(ctx, listSyncObjectsByIDs, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncObject
	for rows.Next() {
		var i KukuSyncObject
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ObjectID,
			&i.ObjectKind,
			&i.StorageProvider,
			&i.StorageKey,
			&i.CiphertextSha256,
			&i.SizeBytes,
			&i.UploadState,
			&i.ErrorReason,
			&i.CreatedByDeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableAt,
			&i.ExpiresAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncWorkspacesByOwner = `-- name: ListSyncWorkspacesByOwner :many
SELECT id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version FROM kuku.sync_workspaces
WHERE owner_user_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at DESC, created_at DESC, id ASC
`

func (q *Queries) ListSyncWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]KukuSyncWorkspace, error) {
	rows, err := q.db.Query(ctx, listSyncWorkspacesByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KukuSyncWorkspace
	for rows.Next() {
		var i KukuSyncWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.CurrentHeadCommitID,
			&i.HeadVersion,
			&i.CryptoVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EncryptedMetadata,
			&i.MetadataVersion,
			&i.EncryptedWorkspaceKey,
			&i.WorkspaceKeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSyncObjectAvailable = `-- name: MarkSyncObjectAvailable :one
UPDATE kuku.sync_objects
SET upload_state = 'available',
    ciphertext_sha256 = $3,
    size_bytes = $4,
    available_at = now(),
    expires_at = NULL,
    error_reason = NULL,
    updated_at = now()
WHERE workspace_id = $1
  AND object_id = $2
  AND upload_state IN ('reserved', 'pending', 'available')
  AND deleted_at IS NULL
RETURNING workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at
`

type MarkSyncObjectAvailableParams struct {
	WorkspaceID      uuid.UUID `json:"workspace_id"`
	ObjectID         string    `json:"object_id"`
	CiphertextSha256 string    `json:"ciphertext_sha256"`
	SizeBytes        int64     `json:"size_bytes"`
}

func (q *Queries) MarkSyncObjectAvailable(ctx context.Context, arg MarkSyncObjectAvailableParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, markSyncObjectAvailable,
		arg.WorkspaceID,
		arg.ObjectID,
		arg.CiphertextSha256,
		arg.SizeBytes,
	)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const markSyncObjectDeleted = `-- name: MarkSyncObjectDeleted :one
UPDATE kuku.sync_objects
SET upload_state = 'deleted',
    expires_at = NULL,
    deleted_at = now(),
    updated_at = now()
WHERE workspace_id = $1
  AND object_id = $2
  AND deleted_at IS NULL
RETURNING workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at
`

type MarkSyncObjectDeletedParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ObjectID    string    `json:"object_id"`
}

func (q *Queries) MarkSyncObjectDeleted(ctx context.Context, arg MarkSyncObjectDeletedParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, markSyncObjectDeleted, arg.WorkspaceID, arg.ObjectID)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const markSyncObjectFailed = `-- name: MarkSyncObjectFailed :one
UPDATE kuku.sync_objects
SET upload_state = 'failed',
    error_reason = $3,
    updated_at = now()
WHERE workspace_id = $1
  AND object_id = $2
  AND deleted_at IS NULL
RETURNING workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at
`

type MarkSyncObjectFailedParams struct {
	WorkspaceID uuid.UUID                     `json:"workspace_id"`
	ObjectID    string                        `json:"object_id"`
	ErrorReason NullKukuSyncObjectErrorReason `json:"error_reason"`
}

func (q *Queries) MarkSyncObjectFailed(ctx context.Context, arg MarkSyncObjectFailedParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, markSyncObjectFailed, arg.WorkspaceID, arg.ObjectID, arg.ErrorReason)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const markSyncObjectPending = `-- name: MarkSyncObjectPending :one
UPDATE kuku.sync_objects
SET upload_state = 'pending',
    ciphertext_sha256 = $3,
    size_bytes = $4,
    expires_at = $5,
    error_reason = NULL,
    updated_at = now()
WHERE workspace_id = $1
  AND object_id = $2
  AND upload_state IN ('reserved', 'pending')
  AND deleted_at IS NULL
RETURNING workspace_id, object_id, object_kind, storage_provider, storage_key, ciphertext_sha256, size_bytes, upload_state, error_reason, created_by_device_id, created_at, updated_at, available_at, expires_at, deleted_at
`

type MarkSyncObjectPendingParams struct {
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	ObjectID         string             `json:"object_id"`
	CiphertextSha256 string             `json:"ciphertext_sha256"`
	SizeBytes        int64              `json:"size_bytes"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) MarkSyncObjectPending(ctx context.Context, arg MarkSyncObjectPendingParams) (KukuSyncObject, error) {
	row := q.db.QueryRow(ctx, markSyncObjectPending,
		arg.WorkspaceID,
		arg.ObjectID,
		arg.CiphertextSha256,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	var i KukuSyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.ObjectID,
		&i.ObjectKind,
		&i.StorageProvider,
		&i.StorageKey,
		&i.CiphertextSha256,
		&i.SizeBytes,
		&i.UploadState,
		&i.ErrorReason,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.ExpiresAt,
		&i.DeletedAt,
	)
	return i, err
}

const markSyncObjectsDeletedByOwner = `-- name: MarkSyncObjectsDeletedByOwner :exec
UPDATE kuku.sync_objects AS o
SET upload_state = 'deleted',
    expires_at = NULL,
    deleted_at = now(),
    updated_at = now()
FROM kuku.sync_workspaces AS w
WHERE o.workspace_id = w.id
  AND w.owner_user_id = $1
  AND o.deleted_at IS NULL
`

func (q *Queries) MarkSyncObjectsDeletedByOwner(ctx context.Context, ownerUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSyncObjectsDeletedByOwner, ownerUserID)
	return err
}

const recalculateSyncUsageAccount = `-- name: RecalculateSyncUsageAccount :one
WITH usage AS (
  SELECT
    COUNT(*) FILTER (
      WHERE w.deleted_at IS NULL
    )::INTEGER AS workspace_count,
    COALESCE(SUM(uw.storage_bytes) FILTER (
      WHERE w.deleted_at IS NULL
    ), 0)::BIGINT AS total_storage_bytes,
    COALESCE(SUM(uw.pending_upload_bytes) FILTER (
      WHERE w.deleted_at IS NULL
    ), 0)::BIGINT AS pending_upload_bytes
  FROM kuku.sync_workspaces w
  LEFT JOIN kuku.sync_usage_workspaces uw
    ON uw.workspace_id = w.id
  WHERE w.owner_user_id = $1
)
UPDATE kuku.sync_usage_accounts AS sua
SET workspace_count = usage.workspace_count,
    total_storage_bytes = usage.total_storage_bytes,
    pending_upload_bytes = usage.pending_upload_bytes,
    updated_at = now()
FROM usage
WHERE sua.user_id = $1
RETURNING sua.user_id, sua.workspace_count, sua.total_storage_bytes, sua.pending_upload_bytes, sua.updated_at
`

func (q *Queries) RecalculateSyncUsageAccount(ctx context.Context, userID uuid.UUID) (KukuSyncUsageAccount, error) {
	row := q.db.QueryRow(ctx, recalculateSyncUsageAccount, userID)
	var i KukuSyncUsageAccount
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceCount,
		&i.TotalStorageBytes,
		&i.PendingUploadBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const recalculateSyncUsageWorkspace = `-- name: RecalculateSyncUsageWorkspace :one
WITH usage AS (
  SELECT
    COALESCE(SUM(size_bytes) FILTER (
      WHERE upload_state = 'available'
        AND deleted_at IS NULL
    ), 0)::BIGINT AS storage_bytes,
    COUNT(*) FILTER (
      WHERE upload_state = 'available'
        AND deleted_at IS NULL
    )::BIGINT AS object_count,
    COALESCE(SUM(size_bytes) FILTER (
      WHERE upload_state = 'pending'
        AND deleted_at IS NULL
    ), 0)::BIGINT AS pending_upload_bytes
  FROM kuku.sync_objects
  WHERE workspace_id = $1
)
UPDATE kuku.sync_usage_workspaces AS suw
SET storage_bytes = usage.storage_bytes,
    object_count = usage.object_count,
    pending_upload_bytes = usage.pending_upload_bytes,
    updated_at = now()
FROM usage
WHERE suw.workspace_id = $1
RETURNING suw.workspace_id, suw.storage_bytes, suw.object_count, suw.pending_upload_bytes, suw.updated_at
`

func (q *Queries) RecalculateSyncUsageWorkspace(ctx context.Context, workspaceID uuid.UUID) (KukuSyncUsageWorkspace, error) {
	row := q.db.QueryRow(ctx, recalculateSyncUsageWorkspace, workspaceID)
	var i KukuSyncUsageWorkspace
	err := row.Scan(
		&i.WorkspaceID,
		&i.StorageBytes,
		&i.ObjectCount,
		&i.PendingUploadBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseSyncUsageAccountPendingBytes = `-- name: ReleaseSyncUsageAccountPendingBytes :exec
UPDATE kuku.sync_usage_accounts
SET pending_upload_bytes = pending_upload_bytes - $2,
    updated_at = now()
WHERE user_id = $1
`

type ReleaseSyncUsageAccountPendingBytesParams struct {
	UserID             uuid.UUID `json:"user_id"`
	PendingUploadBytes int64     `json:"pending_upload_bytes"`
}

func (q *Queries) ReleaseSyncUsageAccountPendingBytes(ctx context.Context, arg ReleaseSyncUsageAccountPendingBytesParams) error {
	_, err := q.db.Exec(ctx, releaseSyncUsageAccountPendingBytes, arg.UserID, arg.PendingUploadBytes)
	return err
}

const releaseSyncUsagePendingBytes = `-- name: ReleaseSyncUsagePendingBytes :exec
UPDATE kuku.sync_usage_workspaces
SET pending_upload_bytes = pending_upload_bytes - $2,
    updated_at = now()
WHERE workspace_id = $1
`

type ReleaseSyncUsagePendingBytesParams struct {
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	PendingUploadBytes int64     `json:"pending_upload_bytes"`
}

func (q *Queries) ReleaseSyncUsagePendingBytes(ctx context.Context, arg ReleaseSyncUsagePendingBytesParams) error {
	_, err := q.db.Exec(ctx, releaseSyncUsagePendingBytes, arg.WorkspaceID, arg.PendingUploadBytes)
	return err
}

const resetSyncUsageAccount = `-- name: ResetSyncUsageAccount :exec
UPDATE kuku.sync_usage_accounts
SET workspace_count = 0,
    total_storage_bytes = 0,
    pending_upload_bytes = 0,
    updated_at = now()
WHERE user_id = $1
`

func (q *Queries) ResetSyncUsageAccount(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetSyncUsageAccount, userID)
	return err
}

const resetSyncUsageWorkspacesByOwner = `-- name: ResetSyncUsageWorkspacesByOwner :exec
UPDATE kuku.sync_usage_workspaces AS suw
SET storage_bytes = 0,
    object_count = 0,
    pending_upload_bytes = 0,
    updated_at = now()
FROM kuku.sync_workspaces AS w
WHERE suw.workspace_id = w.id
  AND w.owner_user_id = $1
`

func (q *Queries) ResetSyncUsageWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetSyncUsageWorkspacesByOwner, ownerUserID)
	return err
}

const revokeSyncDevicesByOwner = `-- name: RevokeSyncDevicesByOwner :exec
UPDATE kuku.sync_devices AS d
SET revoked_at = now(), updated_at = now()
FROM kuku.sync_workspaces AS w
WHERE d.workspace_id = w.id
  AND w.owner_user_id = $1
  AND d.revoked_at IS NULL
`

func (q *Queries) RevokeSyncDevicesByOwner(ctx context.Context, ownerUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSyncDevicesByOwner, ownerUserID)
	return err
}

const softDeleteSyncWorkspace = `-- name: SoftDeleteSyncWorkspace :exec
UPDATE kuku.sync_workspaces
SET deleted_at = now(), updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteSyncWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) SoftDeleteSyncWorkspace(ctx context.Context, arg SoftDeleteSyncWorkspaceParams) error {
	_, err := q.db.Exec(ctx, softDeleteSyncWorkspace, arg.ID, arg.OwnerUserID)
	return err
}

const softDeleteSyncWorkspacesByOwner = `-- name: SoftDeleteSyncWorkspacesByOwner :exec
UPDATE kuku.sync_workspaces
SET deleted_at = now(), updated_at = now()
WHERE owner_user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSyncWorkspacesByOwner(ctx context.Context, ownerUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSyncWorkspacesByOwner, ownerUserID)
	return err
}

const touchSyncDeviceLastSeen = `-- name: TouchSyncDeviceLastSeen :exec
UPDATE kuku.sync_devices
SET last_seen_at = now(), updated_at = now()
WHERE workspace_id = $1
  AND id = $2
  AND user_id = $3
  AND revoked_at IS NULL
`

type TouchSyncDeviceLastSeenParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) TouchSyncDeviceLastSeen(ctx context.Context, arg TouchSyncDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, touchSyncDeviceLastSeen, arg.WorkspaceID, arg.ID, arg.UserID)
	return err
}

const updateSyncDeviceMetadata = `-- name: UpdateSyncDeviceMetadata :one
UPDATE kuku.sync_devices
SET encrypted_device_name = $4,
    metadata_version = $5,
    updated_at = now()
WHERE workspace_id = $1
  AND id = $2
  AND user_id = $3
  AND metadata_version = $6
  AND revoked_at IS NULL
RETURNING id, workspace_id, user_id, signing_public_key, encryption_public_key, encrypted_device_name, last_device_seq, created_at, updated_at, last_seen_at, revoked_at, metadata_version
`

type UpdateSyncDeviceMetadataParams struct {
	WorkspaceID         uuid.UUID `json:"workspace_id"`
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
	EncryptedDeviceName []byte    `json:"encrypted_device_name"`
	MetadataVersion     int64     `json:"metadata_version"`
	MetadataVersion_2   int64     `json:"metadata_version_2"`
}

func (q *Queries) UpdateSyncDeviceMetadata(ctx context.Context, arg UpdateSyncDeviceMetadataParams) (KukuSyncDevice, error) {
	row := q.db.QueryRow(ctx, updateSyncDeviceMetadata,
		arg.WorkspaceID,
		arg.ID,
		arg.UserID,
		arg.EncryptedDeviceName,
		arg.MetadataVersion,
		arg.MetadataVersion_2,
	)
	var i KukuSyncDevice
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.SigningPublicKey,
		&i.EncryptionPublicKey,
		&i.EncryptedDeviceName,
		&i.LastDeviceSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.MetadataVersion,
	)
	return i, err
}

const updateSyncDeviceSequence = `-- name: UpdateSyncDeviceSequence :exec
UPDATE kuku.sync_devices
SET last_device_seq = $4,
    last_seen_at = now(),
    updated_at = now()
WHERE workspace_id = $1
  AND id = $2
  AND user_id = $3
  AND revoked_at IS NULL
`

type UpdateSyncDeviceSequenceParams struct {
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	LastDeviceSeq int64     `json:"last_device_seq"`
}

func (q *Queries) UpdateSyncDeviceSequence(ctx context.Context, arg UpdateSyncDeviceSequenceParams) error {
	_, err := q.db.Exec(ctx, updateSyncDeviceSequence,
		arg.WorkspaceID,
		arg.ID,
		arg.UserID,
		arg.LastDeviceSeq,
	)
	return err
}

const updateSyncWorkspaceHead = `-- name: UpdateSyncWorkspaceHead :one
UPDATE kuku.sync_workspaces
SET current_head_commit_id = $3,
    head_version = head_version + 1,
    updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND deleted_at IS NULL
RETURNING id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version
`

type UpdateSyncWorkspaceHeadParams struct {
	ID                  uuid.UUID   `json:"id"`
	OwnerUserID         uuid.UUID   `json:"owner_user_id"`
	CurrentHeadCommitID pgtype.Text `json:"current_head_commit_id"`
}

func (q *Queries) UpdateSyncWorkspaceHead(ctx context.Context, arg UpdateSyncWorkspaceHeadParams) (KukuSyncWorkspace, error) {
	row := q.db.QueryRow(ctx, updateSyncWorkspaceHead, arg.ID, arg.OwnerUserID, arg.CurrentHeadCommitID)
	var i KukuSyncWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.CurrentHeadCommitID,
		&i.HeadVersion,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EncryptedMetadata,
		&i.MetadataVersion,
		&i.EncryptedWorkspaceKey,
		&i.WorkspaceKeyVersion,
	)
	return i, err
}

const updateSyncWorkspaceKey = `-- name: UpdateSyncWorkspaceKey :one
UPDATE kuku.sync_workspaces
SET encrypted_workspace_key = $3,
    workspace_key_version = $4,
    updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND workspace_key_version = $5
  AND deleted_at IS NULL
RETURNING id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version
`

type UpdateSyncWorkspaceKeyParams struct {
	ID                    uuid.UUID `json:"id"`
	OwnerUserID           uuid.UUID `json:"owner_user_id"`
	EncryptedWorkspaceKey []byte    `json:"encrypted_workspace_key"`
	WorkspaceKeyVersion   int64     `json:"workspace_key_version"`
	WorkspaceKeyVersion_2 int64     `json:"workspace_key_version_2"`
}

func (q *Queries) UpdateSyncWorkspaceKey(ctx context.Context, arg UpdateSyncWorkspaceKeyParams) (KukuSyncWorkspace, error) {
	row := q.db.QueryRow(ctx, updateSyncWorkspaceKey,
		arg.ID,
		arg.OwnerUserID,
		arg.EncryptedWorkspaceKey,
		arg.WorkspaceKeyVersion,
		arg.WorkspaceKeyVersion_2,
	)
	var i KukuSyncWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.CurrentHeadCommitID,
		&i.HeadVersion,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EncryptedMetadata,
		&i.MetadataVersion,
		&i.EncryptedWorkspaceKey,
		&i.WorkspaceKeyVersion,
	)
	return i, err
}

const updateSyncWorkspaceMetadata = `-- name: UpdateSyncWorkspaceMetadata :one
UPDATE kuku.sync_workspaces
SET encrypted_metadata = $3,
    metadata_version = $4,
    updated_at = now()
WHERE id = $1
  AND owner_user_id = $2
  AND metadata_version = $5
  AND deleted_at IS NULL
RETURNING id, owner_user_id, current_head_commit_id, head_version, crypto_version, created_at, updated_at, deleted_at, encrypted_metadata, metadata_version, encrypted_workspace_key, workspace_key_version
`

type UpdateSyncWorkspaceMetadataParams struct {
	ID                uuid.UUID `json:"id"`
	OwnerUserID       uuid.UUID `json:"owner_user_id"`
	EncryptedMetadata []byte    `json:"encrypted_metadata"`
	MetadataVersion   int64     `json:"metadata_version"`
	MetadataVersion_2 int64     `json:"metadata_version_2"`
}

func (q *Queries) UpdateSyncWorkspaceMetadata(ctx context.Context, arg UpdateSyncWorkspaceMetadataParams) (KukuSyncWorkspace, error) {
	row := q.db.QueryRow(ctx, updateSyncWorkspaceMetadata,
		arg.ID,
		arg.OwnerUserID,
		arg.EncryptedMetadata,
		arg.MetadataVersion,
		arg.MetadataVersion_2,
	)
	var i KukuSyncWorkspace
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.CurrentHeadCommitID,
		&i.HeadVersion,
		&i.CryptoVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EncryptedMetadata,
		&i.MetadataVersion,
		&i.EncryptedWorkspaceKey,
		&i.WorkspaceKeyVersion,
	)
	return i, err
}

const upsertSyncAccountKeyEnvelope = `-- name: UpsertSyncAccountKeyEnvelope :one
INSERT INTO kuku.sync_account_key_envelopes (
  user_id,
  account_key_id,
  envelope_id,
  recipient_type,
  key_version,
  kdf_params,
  encrypted_envelope
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, account_key_id, envelope_id)
DO UPDATE SET
  recipient_type = EXCLUDED.recipient_type,
  key_version = EXCLUDED.key_version,
  kdf_params = EXCLUDED.kdf_params,
  encrypted_envelope = EXCLUDED.encrypted_envelope,
  updated_at = now()
RETURNING user_id, account_key_id, envelope_id, recipient_type, key_version, kdf_params, encrypted_envelope, created_at, updated_at
`

type UpsertSyncAccountKeyEnvelopeParams struct {
	UserID            uuid.UUID                       `json:"user_id"`
	AccountKeyID      string                          `json:"account_key_id"`
	EnvelopeID        string                          `json:"envelope_id"`
	RecipientType     KukuSyncAccountKeyRecipientType `json:"recipient_type"`
	KeyVersion        int64                           `json:"key_version"`
	KdfParams         []byte                          `json:"kdf_params"`
	EncryptedEnvelope []byte                          `json:"encrypted_envelope"`
}

func (q *Queries) UpsertSyncAccountKeyEnvelope(ctx context.Context, arg UpsertSyncAccountKeyEnvelopeParams) (KukuSyncAccountKeyEnvelope, error) {
	row := q.db.QueryRow(ctx, upsertSyncAccountKeyEnvelope,
		arg.UserID,
		arg.AccountKeyID,
		arg.EnvelopeID,
		arg.RecipientType,
		arg.KeyVersion,
		arg.KdfParams,
		arg.EncryptedEnvelope,
	)
	var i KukuSyncAccountKeyEnvelope
	err := row.Scan(
		&i.UserID,
		&i.AccountKeyID,
		&i.EnvelopeID,
		&i.RecipientType,
		&i.KeyVersion,
		&i.KdfParams,
		&i.EncryptedEnvelope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSyncDeviceCursor = `-- name: UpsertSyncDeviceCursor :exec
INSERT INTO kuku.sync_device_cursors (
  workspace_id,
  device_id,
  last_seen_commit_id,
  last_seen_checkpoint_commit_id,
  updated_at
)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (workspace_id, device_id)
DO UPDATE SET
  last_seen_commit_id = EXCLUDED.last_seen_commit_id,
  last_seen_checkpoint_commit_id = COALESCE(EXCLUDED.last_seen_checkpoint_commit_id, kuku.sync_device_cursors.last_seen_checkpoint_commit_id),
  updated_at = now()
`

type UpsertSyncDeviceCursorParams struct {
	WorkspaceID                uuid.UUID   `json:"workspace_id"`
	DeviceID                   uuid.UUID   `json:"device_id"`
	LastSeenCommitID           pgtype.Text `json:"last_seen_commit_id"`
	LastSeenCheckpointCommitID pgtype.Text `json:"last_seen_checkpoint_commit_id"`
}

func (q *Queries) UpsertSyncDeviceCursor(ctx context.Context, arg UpsertSyncDeviceCursorParams) error {
	_, err := q.db.Exec(ctx, upsertSyncDeviceCursor,
		arg.WorkspaceID,
		arg.DeviceID,
		arg.LastSeenCommitID,
		arg.LastSeenCheckpointCommitID,
	)
	return err
}

const upsertSyncKeyEnvelope = `-- name: UpsertSyncKeyEnvelope :one
INSERT INTO kuku.sync_key_envelopes (
  workspace_id,
  envelope_id,
  recipient_type,
  recipient_device_id,
  key_version,
  kdf_params,
  encrypted_envelope,
  created_by_device_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (workspace_id, envelope_id)
DO UPDATE SET
  recipient_type = EXCLUDED.recipient_type,
  recipient_device_id = EXCLUDED.recipient_device_id,
  key_version = EXCLUDED.key_version,
  kdf_params = EXCLUDED.kdf_params,
  encrypted_envelope = EXCLUDED.encrypted_envelope,
  created_by_device_id = EXCLUDED.created_by_device_id,
  updated_at = now()
RETURNING workspace_id, envelope_id, recipient_type, recipient_device_id, key_version, kdf_params, encrypted_envelope, created_by_device_id, created_at, updated_at
`

type UpsertSyncKeyEnvelopeParams struct {
	WorkspaceID       uuid.UUID                `json:"workspace_id"`
	EnvelopeID        string                   `json:"envelope_id"`
	RecipientType     KukuSyncKeyRecipientType `json:"recipient_type"`
	RecipientDeviceID uuid.NullUUID            `json:"recipient_device_id"`
	KeyVersion        int64                    `json:"key_version"`
	KdfParams         []byte                   `json:"kdf_params"`
	EncryptedEnvelope []byte                   `json:"encrypted_envelope"`
	CreatedByDeviceID uuid.NullUUID            `json:"created_by_device_id"`
}

func (q *Queries) UpsertSyncKeyEnvelope(ctx context.Context, arg UpsertSyncKeyEnvelopeParams) (KukuSyncKeyEnvelope, error) {
	row := q.db.QueryRow(ctx, upsertSyncKeyEnvelope,
		arg.WorkspaceID,
		arg.EnvelopeID,
		arg.RecipientType,
		arg.RecipientDeviceID,
		arg.KeyVersion,
		arg.KdfParams,
		arg.EncryptedEnvelope,
		arg.CreatedByDeviceID,
	)
	var i KukuSyncKeyEnvelope
	err := row.Scan(
		&i.WorkspaceID,
		&i.EnvelopeID,
		&i.RecipientType,
		&i.RecipientDeviceID,
		&i.KeyVersion,
		&i.KdfParams,
		&i.EncryptedEnvelope,
		&i.CreatedByDeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
